import { DRINKS_BY_ID } from '@/data';
import rawIndex from '@/data/barIndex.json';
import type { Drink } from '@/types';

/* ====================================================================== */
/* My Bar — what you own, and what it lets you make.                      */
/*                                                                        */
/* The index is generated by scripts/build-bar-index.mjs; the reasoning    */
/* about variants, generics and staples lives in that file's header and is */
/* not repeated here. What matters on this side is the SHAPE it produces:  */
/*                                                                        */
/*   slots: string[][]   one entry per thing the drink needs, and each     */
/*                       entry lists every ingredient id that satisfies    */
/*                       it. A slot is met if you own ANY id in it.        */
/*                                                                        */
/* That single shape absorbs all three awkward cases at once — a plain     */
/* requirement is a one-element slot, "Vodka or gin" is a two-element      */
/* slot, and "Rum" is a slot listing every rum. Matching never needs to    */
/* know which of the three it is looking at.                              */
/* ====================================================================== */

export type IngredientCategory =
  | 'spirit' | 'liqueur' | 'wine' | 'bitters' | 'citrus' | 'juice'
  | 'syrup' | 'mixer' | 'dairy' | 'produce' | 'spice' | 'savoury' | 'other';

export interface Ingredient {
  id: string;
  label: string;
  category: IngredientCategory;
  /** How many cocktails name it. Drives the picker's default order. */
  uses: number;
}

interface RawRecipe {
  id: string;
  name: string;
  slots: string[][];
}

const index = rawIndex as unknown as { ingredients: Ingredient[]; recipes: RawRecipe[] };

export const INGREDIENTS: Ingredient[] = index.ingredients;

export const INGREDIENTS_BY_ID: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((i) => [i.id, i]),
);

/**
 * The picker's default view. Everything is searchable, but showing 488
 * ingredients at rest is a wall — and the tail is genuinely obscure
 * (Brennivín appears in two drinks). Anything named by three or more
 * cocktails earns a place in the browse list; the rest is found by typing.
 */
export const COMMON_INGREDIENTS: Ingredient[] = INGREDIENTS.filter((i) => i.uses >= 3);

export const CATEGORY_LABEL: Record<IngredientCategory, string> = {
  spirit: 'Spirits',
  liqueur: 'Liqueurs',
  wine: 'Wine & beer',
  bitters: 'Bitters',
  citrus: 'Citrus',
  juice: 'Juices',
  syrup: 'Syrups & sweeteners',
  mixer: 'Mixers',
  dairy: 'Dairy & eggs',
  produce: 'Fresh',
  spice: 'Spices',
  savoury: 'Savoury',
  other: 'Everything else',
};

/** Display order for the picker's sections. */
export const CATEGORY_ORDER: IngredientCategory[] = [
  'spirit', 'liqueur', 'wine', 'bitters', 'citrus', 'juice',
  'syrup', 'mixer', 'dairy', 'produce', 'spice', 'savoury', 'other',
];

export interface Match {
  drink: Drink;
  /** Ingredient ids you are missing — one per unmet slot. Empty means makeable. */
  missing: string[];
}

export interface BarResult {
  /** Everything you can make right now, rarest-looking first is NOT the order —
   *  these are sorted by name, because the list is browsed not ranked. */
  makeable: Match[];
  /** Missing exactly one thing. The useful half of the feature. */
  nearly: Match[];
  /**
   * Ingredients ranked by how many `nearly` drinks each would unlock. This is
   * the shopping list, and it is the reason `nearly` is computed at all: on a
   * realistic 15-bottle bar it is 207 drinks against 48 makeable ones.
   */
  nextBest: { ingredient: Ingredient; unlocks: number }[];
}

const EMPTY: BarResult = { makeable: [], nearly: [], nextBest: [] };

/**
 * Walks all 882 specs. Cheap enough to run on every change — the whole index
 * is ~3,000 slots — but callers should still memoise on `owned`, because the
 * screen re-renders on every keystroke in the search field.
 */
export function matchBar(owned: ReadonlySet<string>): BarResult {
  if (owned.size === 0) return EMPTY;

  const makeable: Match[] = [];
  const nearly: Match[] = [];

  for (const recipe of index.recipes) {
    const drink = DRINKS_BY_ID[recipe.id];
    if (!drink) continue; // a drink pruned from the index since the last build

    const missing: string[] = [];
    for (const slot of recipe.slots) {
      if (slot.some((id) => owned.has(id))) continue;
      // The first id is the canonical one — the others are family expansions,
      // so naming the generic is what a shopping list should say.
      missing.push(slot[0]);
      if (missing.length > 1) break; // past "nearly", stop counting
    }

    if (missing.length === 0) makeable.push({ drink, missing });
    else if (missing.length === 1) nearly.push({ drink, missing });
  }

  const byName = (a: Match, b: Match) => a.drink.name.localeCompare(b.drink.name);
  makeable.sort(byName);
  nearly.sort(byName);

  const tally = new Map<string, number>();
  for (const m of nearly) tally.set(m.missing[0], (tally.get(m.missing[0]) ?? 0) + 1);

  const nextBest = [...tally.entries()]
    .map(([id, unlocks]) => ({ ingredient: INGREDIENTS_BY_ID[id], unlocks }))
    .filter((x) => x.ingredient)
    .sort((a, b) => b.unlocks - a.unlocks || a.ingredient.label.localeCompare(b.ingredient.label))
    .slice(0, 8);

  return { makeable, nearly, nextBest };
}

/** Case- and accent-insensitive contains, so "creme" finds "Crème de cacao". */
export function searchIngredients(query: string): Ingredient[] {
  const q = query.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  if (!q) return [];
  const hits = INGREDIENTS.filter((i) =>
    i.label.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').includes(q),
  );
  // Prefix matches first — typing "gin" should not bury Gin under Ginger ale.
  return hits
    .sort((a, b) => {
      const ap = a.label.toLowerCase().startsWith(q) ? 0 : 1;
      const bp = b.label.toLowerCase().startsWith(q) ? 0 : 1;
      return ap - bp || b.uses - a.uses || a.label.localeCompare(b.label);
    })
    .slice(0, 40);
}
