from ck import S, T, B, C

# ============================================================ ITALY & ALPS

T("Cardinale", "Italy", "Rome, Italy", "uncommon", "26-28%",
  "A Negroni with dry vermouth in place of sweet. Drier, paler, and sharper at the finish.",
  ["bitter orange", "juniper", "dry herbs"],
  ["Gin", "Campari", "Dry vermouth"],
  "The name is usually traced to the Hotel Excelsior in Rome, where a cardinal is said to have asked for his Negroni without the sweetness.",
  [("Gin", "1 oz / 30 ml"), ("Campari", "1 oz / 30 ml"),
   ("Dry vermouth", "1 oz / 30 ml"), ("Ice", "cubed")],
  "An orange twist", glass="Rocks glass")

B("Pirlo", "Italy", "Brescia, Italy", "Spritz", "uncommon", "8-10%",
  "Still white wine with Campari poured through it and a splash of soda. Brescia's own aperitivo, older than the Venetian spritz.",
  ["bitter orange", "white wine", "soda"], "Wine glass",
  ["White wine", "Campari", "Soda water"],
  "The name comes from the Brescian dialect verb pirlare, to spin — the Campari corkscrews down through the wine as it is poured, which is the whole trick.",
  [("Dry white wine", "3 oz / 90 ml"), ("Campari", "1.5 oz / 45 ml"),
   ("Soda water", "splash"), ("Ice", "cubed")],
  ["Fill a wine glass with ice and add the white wine.",
   "Pour the Campari slowly into the centre so it spirals down through the wine.",
   "Add a small splash of soda.",
   "Do not stir it flat — the descending swirl is the point."],
  "An orange slice")

B("Hugo", "Italy", "South Tyrol, Italy", "Spritz", "common", "8-10%",
  "Prosecco, elderflower, mint and lime over ice. The Alpine answer to the Aperol Spritz, and lighter than any of them.",
  ["elderflower", "mint", "lime", "prosecco"], "Wine glass",
  ["Prosecco", "Elderflower syrup", "Mint", "Lime", "Soda water"],
  "Roland Gruber mixed the first one in Naturns in 2005 and used lemon balm syrup; elderflower only replaced it once the drink spread beyond South Tyrol.",
  [("Prosecco", "3 oz / 90 ml"), ("Elderflower syrup", "0.75 oz / 22 ml"),
   ("Soda water", "1 oz / 30 ml"), ("Lime", "2 wedges"),
   ("Mint leaves", "6"), ("Ice", "cubed")],
  ["Put the mint and lime wedges in a large wine glass and press them once, gently.",
   "Add the elderflower syrup and fill the glass with ice.",
   "Pour in the prosecco, then top with soda water.",
   "Stir once from the bottom and serve with the mint standing proud."],
  "A mint sprig and a lime wedge")

C("Kaisermelange", "Austria", "Vienna, Austria", "Hot", "rare", "6-8%",
  "Black coffee whisked with an egg yolk and honey, laced with brandy. A Viennese coffee house order, not a bar one.",
  ["coffee", "honey", "egg", "cognac"], "Coffee glass",
  ["Coffee", "Egg yolk", "Honey", "Brandy"],
  "Viennese coffee houses run to dozens of named preparations, each with a fixed ratio of coffee to milk to foam — ordering simply a coffee marks you out immediately.",
  [("Hot strong coffee", "5 oz / 150 ml"), ("Egg yolk", "1"),
   ("Honey", "1 tsp"), ("Brandy", "0.75 oz / 22 ml")],
  ["Whisk the egg yolk with the honey until pale and smooth.",
   "Pour a little of the hot coffee in slowly while whisking, to temper the yolk.",
   "Add the brandy and the rest of the coffee, whisking as you go.",
   "Serve in a warmed glass without straining."],
  "None", "built")

C("Kafi Luz", "Switzerland", "Lucerne, Switzerland", "Hot", "rare", "12-14%",
  "Weak coffee with a serious measure of fruit brandy. The house drink of central Swiss village taverns.",
  ["coffee", "pear brandy", "warmth"], "Small glass",
  ["Coffee", "Träsch or kirsch", "Sugar"],
  "It is traditionally poured pale on purpose — the coffee is there to carry the Träsch, the pear-and-apple brandy of central Switzerland, rather than the other way round.",
  [("Hot coffee", "3 oz / 90 ml"), ("Träsch or kirsch", "1.5 oz / 45 ml"),
   ("Sugar", "1 tsp")],
  ["Stir the sugar into the hot coffee until it dissolves.",
   "Add the Trasch and stir once more.",
   "Serve in a small handled glass, hot.",
   "Refills are poured into the same glass without rinsing it."],
  "None", "built")

# ==================================================== GERMANY & THE NORTH

C("Eierpunsch", "Germany", "Germany", "Hot", "uncommon", "8-10%",
  "Hot white wine beaten with egg yolks, sugar and vanilla until thick. The richest thing at a German Christmas market.",
  ["egg", "vanilla", "white wine", "sugar"], "Mug",
  ["White wine", "Egg yolks", "Sugar", "Vanilla"],
  "Christmas market stalls sell it in the same returnable ceramic mug as Glühwein, and the deposit on the mug is often larger than the drink.",
  [("Dry white wine", "6 oz / 180 ml"), ("Egg yolks", "2"),
   ("Sugar", "2 tbsp"), ("Vanilla extract", "0.5 tsp"),
   ("Dark rum", "0.5 oz / 15 ml, optional")],
  ["Whisk the yolks, sugar and vanilla in a bowl until pale.",
   "Heat the wine to just below a simmer, never letting it boil.",
   "Pour the hot wine onto the yolks in a thin stream, whisking constantly.",
   "Return to a low heat and whisk until it thickens enough to coat a spoon.",
   "Pour into a warmed mug and serve at once."],
  "Whipped cream and cinnamon", "boiled")

C("Maibowle", "Germany", "Germany", "Punch & Cobbler", "rare", "9-11%",
  "White wine infused with sweet woodruff and topped with sparkling wine. Made once a year, in May, when the herb is young.",
  ["woodruff", "hay", "white wine", "sparkling"], "Punch bowl",
  ["White wine", "Sweet woodruff", "Sparkling wine", "Sugar"],
  "The woodruff has to be picked before it flowers and wilted for a day first — fresh green leaves give nothing, and too much of it turns the punch bitter.",
  [("Dry white wine", "1 bottle / 750 ml"),
   ("Wilted sweet woodruff", "1 small bunch"), ("Sugar", "2 tbsp"),
   ("Sparkling wine", "1 bottle / 750 ml, chilled")],
  ["Wilt the woodruff for a day, then tie it in a bunch by the stems.",
   "Hang it in the white wine with the cut ends clear of the liquid and steep for no more than 30 minutes.",
   "Lift out the herb and stir in the sugar until dissolved.",
   "Chill thoroughly, then add the sparkling wine just before serving."],
  "A woodruff sprig and a few strawberries", "infused")

B("Diesel", "Germany", "Germany", "Party", "uncommon", "2-3%",
  "Lager and cola, half and half. Ordered without irony in every German pub, and darker than either half suggests.",
  ["malt", "cola", "caramel"], "Pint glass",
  ["Lager", "Cola"],
  "The same mix goes by different names depending on the beer and the region — Krefelder with Altbier, Colaweizen with wheat beer, and Diesel almost everywhere else.",
  [("Pilsner or lager", "half pint / 285 ml"),
   ("Cola", "half pint / 285 ml")],
  ["Chill both thoroughly.",
   "Pour the cola into a tilted pint glass first.",
   "Add the beer slowly down the side to keep the head from running over.",
   "Serve without stirring."],
  "None")

C("Kaffekask", "Sweden", "Sweden", "Hot", "rare", "14-16%",
  "Coffee and brännvin in the same cup, measured by whether you can see a coin at the bottom.",
  ["coffee", "caraway", "warmth"], "Coffee cup",
  ["Coffee", "Brännvin", "Sugar"],
  "The traditional measure is a coin dropped in the empty cup: pour coffee until it disappears, then pour spirit until you can see it again.",
  [("Hot coffee", "4 oz / 120 ml"), ("Brännvin or vodka", "1.5 oz / 45 ml"),
   ("Sugar", "1 tsp, optional")],
  ["Drop a small coin into the bottom of the cup if you are doing it properly.",
   "Pour hot coffee until the coin is no longer visible.",
   "Add brannvin until the coin comes back into view.",
   "Sweeten if you like, and drink it hot."],
  "None", "built")

# ============================================== CENTRAL & EASTERN EUROPE

C("Svařák", "Czechia", "Czechia", "Hot", "uncommon", "8-10%",
  "Czech mulled wine: red wine warmed with cloves, cinnamon and citrus, and poured by the litre at winter markets.",
  ["clove", "cinnamon", "orange", "red wine"], "Mug",
  ["Red wine", "Cloves", "Cinnamon", "Orange"],
  "Czech svařák is usually poured far less sweet than German Glühwein, and market stalls heat it in open vats rather than sealed urns.",
  [("Red wine", "1 bottle / 750 ml"), ("Sugar", "3 tbsp"),
   ("Cinnamon sticks", "2"), ("Cloves", "8"),
   ("Orange", "1, sliced"), ("Star anise", "1")],
  ["Combine everything in a wide pan.",
   "Heat slowly to steaming and hold it there for 20 minutes without boiling.",
   "Taste and add sugar only if it needs it.",
   "Ladle into warmed mugs, spices and all."],
  "An orange slice", "boiled")

C("Hriatô", "Slovakia", "Slovakia", "Hot", "rare", "20-22%",
  "Caramelised sugar, pork fat and borovicka, drunk hot. A mountain drink that makes no apology for any of that.",
  ["caramel", "juniper", "savoury"], "Small mug",
  ["Borovička", "Sugar", "Pork lard", "Water"],
  "It comes from the shepherding regions of Liptov and Orava, where the fat was the point — it was a working drink for cold weather, not a novelty.",
  [("Borovička or slivovica", "2 oz / 60 ml"), ("Sugar", "1 tbsp"),
   ("Pork lard", "1 tsp"), ("Water", "2 oz / 60 ml")],
  ["Melt the sugar in a small pan until it caramelises to a deep amber.",
   "Add the lard and let it melt into the caramel.",
   "Pour in the water carefully — it will spit — and stir until smooth.",
   "Take it off the heat, add the spirit, and serve hot with a slice of bread."],
  "None", "boiled")

C("Šumadijski Čaj", "Serbia", "Šumadija, Serbia", "Hot", "rare", "22-24%",
  "Serbian tea, which contains no tea. Rakija heated with sugar and honey until it looks entirely innocent.",
  ["plum", "honey", "caramel"], "Small mug",
  ["Rakija", "Sugar", "Honey"],
  "The name is the joke: it arrives the colour of tea, in a tea glass, and is drunk in tea-sized sips for reasons that become clear quickly.",
  [("Šljivovica rakija", "3 oz / 90 ml"), ("Sugar", "1 tbsp"),
   ("Honey", "1 tsp"), ("Water", "1 oz / 30 ml")],
  ["Caramelise the sugar in a small pan until amber.",
   "Add the water and stir until the caramel dissolves again.",
   "Pour in the rakija and warm it through without letting it boil off.",
   "Stir in the honey and serve hot in a small glass."],
  "None", "boiled")

# ================================================== MIDDLE EAST & ASIA

C("Arak Limonana", "Israel", "Tel Aviv, Israel", "Frozen", "uncommon", "12-14%",
  "Frozen mint lemonade with arak poured through it. The drink Tel Aviv runs on between May and October.",
  ["anise", "mint", "lemon"], "Highball glass",
  ["Arak", "Lemon juice", "Mint", "Sugar"],
  "Limonana is a coined word — limon plus nana, lemon plus mint — invented for an Israeli advertising campaign in the 1990s that sold a drink which did not exist yet.",
  [("Arak", "2 oz / 60 ml"), ("Lemon juice", "1.5 oz / 45 ml"),
   ("Mint leaves", "20"), ("Simple syrup", "1 oz / 30 ml"),
   ("Ice", "1.5 cups, crushed")],
  ["Blend the lemon juice, mint, syrup and ice until slushy and bright green.",
   "Pour into a tall glass.",
   "Pour the arak over the top and watch it turn the surface milky.",
   "Serve with a spoon and a straw."],
  "A mint sprig", "blended")

B("Yakult Soju", "South Korea", "Seoul, South Korea", "Party", "uncommon", "8-10%",
  "Soju, cultured yoghurt drink and lemon-lime soda. Pale pink, deceptively easy, and a fixture of Korean drinking nights.",
  ["yoghurt", "citrus", "sweet"], "Highball glass",
  ["Soju", "Yakult", "Lemon-lime soda"],
  "The yoghurt drink was never meant for this — its role is to round off soju's sharp edge, which it does so well that the alcohol becomes very hard to taste.",
  [("Soju", "2 oz / 60 ml"), ("Yakult", "2 bottles / 130 ml"),
   ("Lemon-lime soda", "3 oz / 90 ml"), ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the soju and the Yakult and stir once.",
   "Top with lemon-lime soda.",
   "Serve immediately, while it is still cold enough to hide itself."],
  "None")

B("Poktanju", "South Korea", "Seoul, South Korea", "Shot", "uncommon", "8-10%",
  "A shot glass of soju or whisky dropped into a glass of beer, and drunk in one go. The bomb drink.",
  ["malt", "grain", "sharp"], "Beer glass",
  ["Soju", "Beer"],
  "Poktanju is the dropped version and somaek the poured one — the distinction matters at a Korean table, where the pouring itself carries a full set of manners.",
  [("Lager", "6 oz / 180 ml"), ("Soju or whisky", "1.5 oz / 45 ml")],
  ["Pour the beer into a glass, leaving room at the top.",
   "Rest a filled shot glass on the rim, or drop it in from a height.",
   "Let it settle for a second — it will foam hard.",
   "Drink it down in one, which is not optional."],
  "None")

C("Subak Soju", "South Korea", "Seoul, South Korea", "Frozen", "uncommon", "6-8%",
  "A hollowed watermelon filled with its own blended flesh and soju, and served back in the rind.",
  ["watermelon", "sweet", "grain"], "Watermelon shell",
  ["Soju", "Watermelon"],
  "It is sold that way in Korean pubs — the emptied melon comes to the table as the vessel, with ladles, and is shared between four or more people.",
  [("Watermelon", "1 small"), ("Soju", "1 bottle / 360 ml"),
   ("Ice", "cubed")],
  ["Cut the top off the watermelon and scoop out the flesh, keeping the shell whole.",
   "Blend the flesh smooth and strain out the seeds.",
   "Stir the juice together with the soju and pour it back into the shell.",
   "Add ice and serve with a ladle and several glasses."],
  "The watermelon lid, set back on top", "blended")

B("Arak Attack", "Indonesia", "Bali, Indonesia", "Regional", "uncommon", "14-16%",
  "Balinese arak with orange juice and a red float. The cheapest drink on Bali and the one most travellers meet first.",
  ["palm spirit", "orange", "grenadine"], "Highball glass",
  ["Arak", "Orange juice", "Grenadine"],
  "Balinese arak is distilled from palm sap or rice and varies wildly by producer, which is why the orange juice is doing more work than it appears to be.",
  [("Balinese arak", "2 oz / 60 ml"), ("Orange juice", "4 oz / 120 ml"),
   ("Grenadine", "0.25 oz / 7 ml"), ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the arak and top with orange juice.",
   "Stir once to combine.",
   "Trickle the grenadine down the inside so it settles at the bottom."],
  "An orange slice")

S("Arrack Sour", "Sri Lanka", "Sri Lanka", "uncommon", "20-22%",
  "Ceylon coconut arrack with lime and sugar. A sour built on a spirit made from the sap of a flower.",
  ["coconut", "lime", "toffee"],
  ["Coconut arrack", "Lime juice", "Simple syrup"],
  "Sri Lankan arrack is distilled from the sap of unopened coconut flowers, tapped by climbers who move between treetops on ropes strung across the canopy.",
  [("Coconut arrack", "2 oz / 60 ml"), ("Lime juice", "0.75 oz / 22 ml"),
   ("Simple syrup", "0.5 oz / 15 ml"), ("Ice", "cubed")],
  "A lime wheel")

# ============================================== LATIN AMERICA & CARIBBEAN

B("Bandera", "Mexico", "Jalisco, Mexico", "Shot", "uncommon", "38-40%",
  "Three glasses in a row — lime, blanco tequila and sangrita — arranged in the colours of the Mexican flag.",
  ["lime", "agave", "tomato", "chilli"], "Three shot glasses",
  ["Tequila", "Lime juice", "Sangrita"],
  "It is not a shot to be thrown back: the order is meant to be sipped in rotation, and the sangrita is the chaser, never the mixer.",
  [("Blanco tequila", "1.5 oz / 45 ml"), ("Lime juice", "1.5 oz / 45 ml"),
   ("Sangrita", "1.5 oz / 45 ml")],
  ["Line up three shot glasses left to right.",
   "Fill the first with lime juice, the second with blanco tequila, the third with sangrita.",
   "Sip from each in turn rather than drinking any of them down.",
   "Refill whichever empties first."],
  "None")

C("Batida", "Brazil", "São Paulo, Brazil", "Frozen", "uncommon", "14-16%",
  "Cachaça blended with fruit and sweetened condensed milk until it is thick enough to stand a straw in.",
  ["coconut", "cachaca", "condensed milk"], "Highball glass",
  ["Cachaça", "Fruit", "Condensed milk"],
  "Batida simply means shaken, and the form takes any fruit at all — coconut, passion fruit, tamarind, cashew fruit — with condensed milk as the constant.",
  [("Cachaça", "2 oz / 60 ml"), ("Coconut milk", "3 oz / 90 ml"),
   ("Sweetened condensed milk", "1 oz / 30 ml"), ("Ice", "1 cup")],
  ["Put everything in a blender.",
   "Blend until completely smooth and thick.",
   "Pour into a tall glass without straining.",
   "Serve with a wide straw."],
  "Grated coconut", "blended")

B("Ponche a la Romana", "Chile", "Chile", "Sparkling", "uncommon", "8-10%",
  "Sparkling wine poured over pineapple ice cream. Chile drinks it at New Year and at every national holiday.",
  ["pineapple", "cream", "sparkling"], "Coupe glass",
  ["Sparkling wine", "Pineapple ice cream"],
  "The name points at Rome and the drink has nothing to do with it — the Chilean version fixed on pineapple ice cream and never looked back.",
  [("Sparkling wine", "4 oz / 120 ml, chilled"),
   ("Pineapple ice cream", "2 scoops")],
  ["Put two scoops of pineapple ice cream in a wide chilled glass.",
   "Pour the sparkling wine slowly over the top so it foams up but does not spill.",
   "Let it sit for a moment until the ice cream starts to soften at the edges.",
   "Serve with both a spoon and a straw."],
  "None")

B("Papelón con Limón y Ron", "Venezuela", "Venezuela", "Regional", "uncommon", "12-14%",
  "Raw cane sugar dissolved in water with lime, poured over ice and cut with rum.",
  ["cane sugar", "lime", "molasses"], "Highball glass",
  ["Papelón", "Lime juice", "Rum", "Water"],
  "Papelón is unrefined cane sugar sold in solid cones; it has to be dissolved in warm water first, and it tastes nothing like white sugar syrup.",
  [("Papelón or panela", "2 oz / 60 g, grated"), ("Warm water", "5 oz / 150 ml"),
   ("Lime juice", "1 oz / 30 ml"), ("White rum", "1.5 oz / 45 ml"),
   ("Ice", "cubed")],
  ["Dissolve the grated papelon in the warm water and let it cool completely.",
   "Add the lime juice and stir.",
   "Fill a tall glass with ice and pour the mixture over.",
   "Add the rum and stir once more."],
  "A lime wheel")

B("Rum and Ting", "Jamaica", "Jamaica", "Highball", "uncommon", "14-16%",
  "Overproof white rum with Ting, the Jamaican grapefruit soda. Two ingredients, no ceremony.",
  ["grapefruit", "overproof rum", "bitter"], "Highball glass",
  ["White overproof rum", "Ting"],
  "Ting is made with real grapefruit juice and is bracingly bitter, which is the only reason it can stand up to 63 percent rum.",
  [("White overproof rum", "1.5 oz / 45 ml"),
   ("Ting grapefruit soda", "6 oz / 180 ml"), ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the rum.",
   "Top with cold Ting.",
   "Stir once and add a squeeze of lime if the soda is very sweet."],
  "A lime wedge")

S("Ponche de Crème", "Trinidad and Tobago", "Trinidad", "uncommon", "14-16%",
  "Trinidad's Christmas drink: eggs, condensed milk, rum and a heavy hand with the Angostura.",
  ["condensed milk", "nutmeg", "rum", "bitters"],
  ["Eggs", "Condensed milk", "Rum", "Angostura bitters"],
  "Angostura bitters have been made in Trinidad since 1875, and in a Ponche de Creme they are a measured ingredient rather than a dash.",
  [("Eggs", "4"), ("Sweetened condensed milk", "14 oz / 400 g"),
   ("Evaporated milk", "6 oz / 180 ml"), ("Dark rum", "6 oz / 180 ml"),
   ("Angostura bitters", "1 tsp"), ("Lime zest", "from 1 lime"),
   ("Nutmeg", "to grate")],
  "Grated nutmeg",
  sub="Creamy & Dessert", glass="Small glass",
  steps=["Beat the eggs with the lime zest until completely smooth and pale.",
         "Whisk in both milks, then the rum, then the bitters.",
         "Strain through a fine sieve to catch the zest and any thread of egg.",
         "Chill for at least a day before serving — it thickens and settles as it rests.",
         "Serve cold, over one cube of ice, with nutmeg over the top."])

C("Springbok", "South Africa", "South Africa", "Shot", "uncommon", "20-22%",
  "Green crème de menthe under a layer of Amarula, poured to the colours of the national rugby jersey.",
  ["mint", "cream", "marula"], "Shot glass",
  ["Crème de menthe", "Amarula"],
  "Amarula is made from the fruit of the marula tree, which grows wild across southern Africa and is harvested from the ground rather than picked.",
  [("Green crème de menthe", "0.75 oz / 22 ml"),
   ("Amarula cream liqueur", "0.75 oz / 22 ml")],
  ["Pour the crème de menthe into a shot glass.",
   "Rest a barspoon just above the surface, curve up.",
   "Pour the Amarula slowly over the back of it so it floats in a clean layer.",
   "Serve without disturbing the line between them."],
  "None", "layered")

S("Yungueño", "Bolivia", "Yungas, Bolivia", "rare", "16-18%",
  "Singani shaken with orange juice. Bolivia's most-drunk mixed drink, named for the valleys east of La Paz.",
  ["orange", "singani", "muscat"],
  ["Singani", "Orange juice", "Sugar"],
  "Singani is distilled only from Muscat of Alexandria grown above 1,600 metres, which makes it one of the few spirits with altitude written into its legal definition.",
  [("Singani", "2 oz / 60 ml"), ("Orange juice", "3 oz / 90 ml"),
   ("Simple syrup", "0.25 oz / 7 ml"), ("Ice", "cubed")],
  "An orange wheel", sub="Regional", glass="Rocks glass")

B("Vermut de Grifo", "Spain", "Barcelona, Spain", "Regional", "uncommon", "14-16%",
  "Draught vermouth poured over ice with soda, an olive and a slice of orange. Sunday at noon, in Barcelona.",
  ["red vermouth", "orange", "olive"], "Rocks glass",
  ["Red vermouth", "Soda water", "Olive", "Orange"],
  "Fer el vermut means the hour before lunch rather than the drink itself, and bars that pour it from the tap advertise the fact on the door.",
  [("Red vermouth", "3 oz / 90 ml"), ("Soda water", "splash"),
   ("Ice", "cubed"), ("Green olive", "1"), ("Orange", "1 slice")],
  ["Fill a rocks glass with ice.",
   "Pour the vermouth over it.",
   "Add a short splash of soda — enough to lift it, not to dilute it.",
   "Drop in an olive and hang an orange slice on the rim."],
  "A green olive and an orange slice")

S("Sour de Maracuyá", "Peru", "Lima, Peru", "uncommon", "18-20%",
  "A Pisco Sour rerouted through passion fruit. Sharper, more floral, and harder to stop at one.",
  ["passion fruit", "pisco", "lime", "egg white"],
  ["Pisco", "Passion fruit", "Lime juice", "Egg white"],
  "Peruvian pisco is never diluted or aged in wood after distillation, so the fruit in a sour has nothing to hide behind.",
  [("Pisco", "2 oz / 60 ml"), ("Passion fruit pulp", "1 oz / 30 ml"),
   ("Lime juice", "0.75 oz / 22 ml"), ("Simple syrup", "0.75 oz / 22 ml"),
   ("Egg white", "1"), ("Angostura bitters", "3 drops"), ("Ice", "cubed")],
  "Three drops of Angostura bitters on the foam",
  steps=["Dry-shake everything but the bitters, without ice, for 15 seconds.",
         "Add ice and shake hard until the tin frosts.",
         "Double-strain into a chilled coupe and let the foam settle.",
         "Drop three dashes of Angostura onto the foam."])
