# -*- coding: utf-8 -*-
from ck import S, T, B, C, FL

US, UK, MX = "USA", "United Kingdom", "Mexico"
NYC, NOLA = "New York City, USA", "New Orleans, USA"
LDN = "London, England"

# ================================================== JERRY THOMAS, 1862

S("Brace Up", US, NYC, "rare", "20-22%",
  "Brandy, absinthe, egg and lemon shaken to a froth. Thomas files it under morning drinks, which tells you what it was for.",
  ["cognac", "anise", "egg", "lemon"],
  ["Brandy", "Absinthe", "Whole egg", "Lemon juice"],
  "The 1862 book groups a whole shelf of these under recuperatives, and every one of them contains raw egg — the Victorian bar's entire theory of the morning after.",
  [("Cognac", "2 oz / 60 ml"), ("Absinthe", "2 dashes"),
   ("Whole egg", "1"), ("Lemon juice", "0.5 oz / 15 ml"),
   ("Simple syrup", "0.5 oz / 15 ml"), ("Angostura bitters", "2 dashes"),
   ("Ice", "cubed")],
  "Grated nutmeg", sub="Brunch", glass="Small tumbler",
  steps=["Dry-shake everything without ice for 20 seconds.",
         "Add ice and shake hard until the tin frosts over.",
         "Strain into a small tumbler.",
         "Grate nutmeg heavily over the top and drink it standing up."])

B("Jersey Cocktail", US, "New Jersey, USA", "Retro", "rare", "5-7%",
  "Hard cider with sugar and bitters. A cocktail by the 1862 definition, built on cider instead of spirit.",
  ["apple", "bitters", "sugar"], "Rocks glass",
  ["Hard cider", "Sugar", "Angostura bitters"],
  "It qualifies as a cocktail on the original terms — a base, sugar, water and bitters — and proves the definition never actually required a distilled spirit.",
  [("Dry hard cider", "4 oz / 120 ml"), ("Simple syrup", "1 tsp"),
   ("Angostura bitters", "2 dashes"), ("Ice", "cubed")],
  ["Stir the syrup and bitters together in the bottom of a rocks glass.",
   "Add ice.",
   "Pour the cider over slowly so it keeps some of its bubble.",
   "Twist a lemon peel over the top and drop it in."],
  "A lemon twist")

C("Hot Spiced Rum", US, "New England, USA", "Hot", "rare", "18-20%",
  "Rum, butter, sugar and spice under boiling water. The buttered rum before anyone shortened the name.",
  ["molasses", "butter", "clove", "nutmeg"], "Mug",
  ["Dark rum", "Butter", "Brown sugar", "Cloves"],
  "The butter is not a garnish or a modern flourish — Thomas prints it in 1862, and it is what keeps the drink from tasting thin.",
  [("Dark rum", "2 oz / 60 ml"), ("Brown sugar", "1 tbsp"),
   ("Unsalted butter", "1 tsp"), ("Cloves", "3"),
   ("Cinnamon stick", "1"), ("Boiling water", "4 oz / 120 ml")],
  ["Put the sugar, butter, cloves and cinnamon in a warmed mug.",
   "Add a splash of boiling water and mash it into a paste.",
   "Pour in the rum and stir.",
   "Top with the rest of the boiling water and grate nutmeg over."],
  "Grated nutmeg and a cinnamon stick", "built")

S("Champagne Cobbler", US, NYC, "rare", "10-12%",
  "Champagne over crushed ice with curaçao and fruit. The cobbler template applied to the most expensive bottle in the room.",
  ["brioche", "orange", "berry"],
  ["Champagne", "Orange curaçao", "Fruit", "Sugar"],
  "The cobbler was the drink that sold the straw — it was among the first served with one, because crushed ice made it impossible to drink any other way.",
  [("Champagne", "4 oz / 120 ml"), ("Orange curaçao", "0.5 oz / 15 ml"),
   ("Simple syrup", "1 tsp"), ("Orange", "2 slices"),
   ("Ice", "crushed")],
  "Seasonal fruit and a mint sprig",
  sub="Julep & Cobbler", glass="Goblet", method="built",
  steps=["Fill a goblet with crushed ice.",
         "Add the curaçao and syrup and stir once.",
         "Pour the champagne slowly over the ice so it does not foam over.",
         "Pile fruit and mint on top and add a straw."])

S("Port Cobbler", US, NYC, "rare", "12-14%",
  "Port, sugar and fruit churned through crushed ice. Sweeter and heavier than the sherry version, and older.",
  ["port", "berry", "orange"],
  ["Port wine", "Sugar", "Orange", "Fruit"],
  "Cobblers were the most-ordered American drink of the 1840s, and the sherry version in particular was what a nineteenth-century bar sold most of.",
  [("Ruby port", "3 oz / 90 ml"), ("Simple syrup", "0.5 oz / 15 ml"),
   ("Orange", "2 slices"), ("Ice", "crushed")],
  "Berries, an orange slice and mint",
  sub="Julep & Cobbler", glass="Goblet", method="built",
  steps=["Muddle the orange slices with the syrup in the bottom of a goblet.",
         "Fill the glass with crushed ice.",
         "Add the port and churn with a barspoon until the glass frosts.",
         "Cap with more ice, pile fruit on top and add a straw."])

S("Gin Smash", US, NYC, "rare", "22-24%",
  "Gin, mint and sugar over crushed ice. A julep in a short glass, which is the only difference there has ever been.",
  ["mint", "juniper", "sugar"],
  ["Gin", "Mint", "Sugar"],
  "The old books separate smash from julep purely by glass size — a smash is a short drink and a julep a long one, and nothing else about them differs.",
  [("Gin", "2 oz / 60 ml"), ("Simple syrup", "0.5 oz / 15 ml"),
   ("Mint leaves", "8"), ("Ice", "crushed")],
  "A mint bouquet",
  sub="Julep & Cobbler", glass="Rocks glass", method="muddled",
  steps=["Press the mint gently with the syrup in a rocks glass.",
         "Add the gin and fill with crushed ice.",
         "Churn with a barspoon until the outside of the glass frosts.",
         "Cap with more ice and crown with mint."])

C("Santina's Pousse Café", US, NOLA, "Creamy & Dessert", "rare", "26-28%",
  "Brandy, maraschino and curaçao floated in three clean bands. Named for the New Orleans bartender who worked out how to do it.",
  ["orange", "cherry", "cognac"], "Pony glass",
  ["Brandy", "Maraschino liqueur", "Orange curaçao"],
  "Layering works on sugar content rather than alcohol — the sweeter a liqueur, the denser it is, which is why the syrups always go in first.",
  [("Orange curaçao", "0.5 oz / 15 ml"), ("Maraschino liqueur", "0.5 oz / 15 ml"),
   ("Cognac", "0.5 oz / 15 ml")],
  ["Pour the curaçao into a narrow pony glass.",
   "Rest a barspoon just above the surface, curve upward, and pour the maraschino over the back of it.",
   "Float the cognac last, the same way.",
   "Serve without a stirrer — disturbing the layers ruins the drink."],
  "None — the three bands are the drink", "layered")

C("Pousse Café", US, NOLA, "Creamy & Dessert", "rare", "24-26%",
  "Five or more liqueurs floated in bands, poured heaviest first. Entirely about the pour and not at all about the taste.",
  ["grenadine", "chocolate", "herbal", "cream"], "Pony glass",
  ["Grenadine", "Crème de cacao", "Green Chartreuse", "Brandy"],
  "The name means push the coffee — it was served after dinner, alongside coffee, and the more bands a bartender could hold apart the better their reputation.",
  [("Grenadine", "0.4 oz / 12 ml"), ("Brown crème de cacao", "0.4 oz / 12 ml"),
   ("Green Chartreuse", "0.4 oz / 12 ml"), ("Orange curaçao", "0.4 oz / 12 ml"),
   ("Brandy", "0.4 oz / 12 ml")],
  ["Pour the grenadine into a tall narrow glass — it is the densest and goes first.",
   "Float each of the others in turn over the back of a barspoon, in the order given.",
   "Pour slowly enough that the stream never breaks the layer beneath.",
   "Serve upright and do not move it quickly."],
  "None", "layered")

C("Angel's Kiss", US, NYC, "Creamy & Dessert", "rare", "18-20%",
  "Crème de cacao under a float of cream, with a cherry balanced on top. A pousse-café with only two bands.",
  ["chocolate", "cream", "cherry"], "Pony glass",
  ["Crème de cacao", "Cream"],
  "It is the simplest drink in the pousse-café family and the one people actually learn on — two liqueurs are hard enough to keep apart.",
  [("Brown crème de cacao", "0.75 oz / 22 ml"),
   ("Double cream", "0.5 oz / 15 ml"), ("Maraschino cherry", "1")],
  ["Pour the crème de cacao into a narrow glass.",
   "Float the cream over the back of a barspoon so it sits in a clean band.",
   "Balance a cherry on the surface of the cream.",
   "Serve without a straw."],
  "A maraschino cherry", "layered")

S("Widow's Dream", UK, LDN, "rare", "16-18%",
  "Bénédictine shaken with a whole egg and cream. Rich, herbal and almost a dessert.",
  ["honey", "herbal", "egg", "cream"],
  ["Bénédictine", "Whole egg", "Cream"],
  "Bénédictine's recipe is genuinely secret — the company says three people know it, and holds that only one of them travels at a time.",
  [("Bénédictine", "2 oz / 60 ml"), ("Whole egg", "1"),
   ("Double cream", "0.5 oz / 15 ml"), ("Ice", "cubed")],
  "Grated nutmeg", sub="Creamy & Dessert",
  steps=["Dry-shake the Bénédictine and egg without ice for 20 seconds.",
         "Add ice and shake hard until cold.",
         "Strain into a chilled coupe.",
         "Float the cream over the back of a spoon and grate nutmeg over."])

T("Rock and Rye", US, NYC, "rare", "30-32%",
  "Rye infused with rock candy and fruit. Sold as a cold remedy for most of the nineteenth century, and taxed as one.",
  ["rye", "citrus", "rock sugar", "clove"],
  ["Rye whiskey", "Rock candy syrup", "Orange", "Lemon"],
  "It was marketed as medicine to dodge liquor law, and bottles carried a label claiming it cured colds — which is how a cocktail ended up behind a pharmacy counter.",
  [("Rye whiskey", "2 oz / 60 ml"), ("Rock candy syrup", "0.5 oz / 15 ml"),
   ("Orange peel", "1 strip"), ("Lemon peel", "1 strip"),
   ("Angostura bitters", "2 dashes"), ("Ice", "cubed")],
  "An orange twist", glass="Rocks glass")

# ================================================= PUNCH, POSSET, BROSE

C("Barbados Rum Punch", "Barbados", "Barbados", "Punch & Cobbler", "uncommon", "18-20%",
  "One of sour, two of sweet, three of strong, four of weak. The rhyme is the recipe.",
  ["lime", "molasses", "nutmeg", "bitters"], "Rocks glass",
  ["Rum", "Lime juice", "Sugar syrup", "Water"],
  "The rhyme is taught to Barbadian children and printed on tea towels, and it scales to any quantity because the ratio is the entire specification.",
  [("Lime juice", "1 oz / 30 ml"), ("Sugar syrup", "2 oz / 60 ml"),
   ("Barbadian rum", "3 oz / 90 ml"), ("Water", "4 oz / 120 ml"),
   ("Angostura bitters", "4 dashes"), ("Ice", "cubed"), ("Nutmeg", "to grate")],
  ["Combine the lime, syrup, rum and water in a jug and stir.",
   "Add the bitters and stir again — Angostura is not optional here.",
   "Pour over ice in short glasses.",
   "Grate nutmeg heavily over each one."],
  "Grated nutmeg and a lime wheel", "built")

C("Caudle", UK, "England", "Hot", "rare", "8-10%",
  "Hot spiced wine or ale thickened with egg and oatmeal. Half a drink, half a meal, and given to the sick for six hundred years.",
  ["oat", "wine", "nutmeg", "egg"], "Mug",
  ["Wine", "Egg yolks", "Oatmeal", "Sugar"],
  "Caudle and posset are sisters — a posset is curdled with wine, a caudle thickened with grain, and both were served to women after childbirth well into the 1800s.",
  [("Sweet white wine", "8 oz / 240 ml"), ("Fine oatmeal", "2 tbsp"),
   ("Egg yolks", "2"), ("Sugar", "2 tbsp"),
   ("Nutmeg", "0.25 tsp"), ("Water", "4 oz / 120 ml")],
  ["Simmer the oatmeal in the water until it thickens into a thin gruel.",
   "Beat the yolks with the sugar and nutmeg.",
   "Warm the wine and whisk it into the gruel, then temper in the yolks off the heat.",
   "Return to a very low heat and stir until it coats a spoon. Do not let it boil."],
  "Grated nutmeg", "boiled")

C("Athol Brose", UK, "Scotland", "Creamy & Dessert", "rare", "16-18%",
  "Whisky, honey and cream over strained oatmeal. Scotland's contribution to the flip family, made without an egg.",
  ["oat", "honey", "malt", "cream"], "Small glass",
  ["Scotch whisky", "Honey", "Oatmeal", "Cream"],
  "The legend has a Highland earl filling a rival's drinking well with it in 1475 and capturing him while he stopped to drink — which is the best defence of the recipe available.",
  [("Steel-cut oatmeal", "4 tbsp"), ("Water", "8 oz / 240 ml"),
   ("Heather honey", "3 tbsp"), ("Scotch whisky", "6 oz / 180 ml"),
   ("Double cream", "3 oz / 90 ml")],
  ["Steep the oatmeal in the water overnight, then strain and keep the liquid.",
   "Stir the honey into the oat water until fully dissolved.",
   "Add the whisky and stir.",
   "Whip the cream to soft peaks, fold it through, and chill before serving."],
  "Grated nutmeg", "infused")

# =========================================================== CHAMPAGNE

S("French 76", "France", "Paris, France", "uncommon", "14-16%",
  "The French 75 with vodka. Cleaner, colder and with nothing in the way of the champagne.",
  ["lemon", "champagne", "sugar"],
  ["Vodka", "Lemon juice", "Simple syrup", "Champagne"],
  "The 75 family is numbered by artillery calibre, and the variants that followed kept the joke going by picking bigger guns.",
  [("Vodka", "1.5 oz / 45 ml"), ("Lemon juice", "0.5 oz / 15 ml"),
   ("Simple syrup", "0.5 oz / 15 ml"), ("Champagne", "3 oz / 90 ml, to top"),
   ("Ice", "cubed")],
  "A lemon twist", sub="Sparkling", glass="Flute",
  steps=["Shake the vodka, lemon juice and syrup with ice.",
         "Strain into a chilled flute.",
         "Top slowly with champagne so it does not overflow.",
         "Express a lemon twist over the top and drop it in."])

S("French 125", "France", "Paris, France", "rare", "16-18%",
  "The French 75 rebuilt on cognac, which is what many argue it should have been all along.",
  ["cognac", "lemon", "champagne"],
  ["Cognac", "Lemon juice", "Simple syrup", "Champagne"],
  "Whether the original took gin or cognac has been argued for a century; the cognac version at least puts a French spirit in a French drink.",
  [("Cognac", "1.5 oz / 45 ml"), ("Lemon juice", "0.5 oz / 15 ml"),
   ("Simple syrup", "0.5 oz / 15 ml"), ("Champagne", "3 oz / 90 ml, to top"),
   ("Ice", "cubed")],
  "A lemon twist", sub="Sparkling", glass="Flute",
  steps=["Shake the cognac, lemon juice and syrup hard with ice.",
         "Strain into a chilled flute.",
         "Top slowly with champagne.",
         "Express a lemon twist over the surface and drop it in."])

# ================================================================ AGAVE

T("Agavoni", UK, LDN, "uncommon", "26-28%",
  "A Negroni with tequila in place of gin. Same equal thirds, more earth underneath.",
  ["agave", "bitter orange", "sweet vermouth"],
  ["Tequila", "Campari", "Sweet vermouth"],
  "Blanco tequila carries the vegetal edge of cooked agave straight through, which is exactly what Campari's bitterness has something to hold on to.",
  [("Blanco tequila", "1 oz / 30 ml"), ("Campari", "1 oz / 30 ml"),
   ("Sweet vermouth", "1 oz / 30 ml"), ("Ice", "cubed")],
  "An orange twist", glass="Rocks glass")

S("Tequila Sour", MX, "Jalisco, Mexico", "uncommon", "18-20%",
  "Tequila, lemon and sugar with egg white. The sour template on agave, and a Margarita's plainer cousin.",
  ["agave", "lemon", "sugar"],
  ["Tequila", "Lemon juice", "Simple syrup", "Egg white"],
  "Lemon rather than lime is what separates this from a Margarita — swap the citrus and the drink stops tasting Mexican and starts tasting like a whiskey sour.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Lemon juice", "0.75 oz / 22 ml"),
   ("Simple syrup", "0.5 oz / 15 ml"), ("Egg white", "1"),
   ("Ice", "cubed")],
  "An orange slice and a cherry",
  steps=["Dry-shake everything without ice for 15 seconds.",
         "Add ice and shake hard until the tin frosts.",
         "Double-strain into a chilled coupe.",
         "Let the foam settle before garnishing."])

S("Mezcal Sour", MX, "Oaxaca, Mexico", "uncommon", "18-20%",
  "Mezcal, lime and agave syrup under an egg-white foam that carries the smoke straight up.",
  ["smoke", "lime", "agave"],
  ["Mezcal", "Lime juice", "Agave syrup", "Egg white"],
  "The smoke is not added — mezcal agave is roasted in earth pits lined with hot stones, and the flavour comes from a week underground.",
  [("Mezcal", "2 oz / 60 ml"), ("Lime juice", "0.75 oz / 22 ml"),
   ("Agave syrup", "0.5 oz / 15 ml"), ("Egg white", "1"),
   ("Ice", "cubed")],
  "A dusting of chilli salt on the foam",
  steps=["Dry-shake everything without ice for 15 seconds.",
         "Add ice and shake hard until very cold.",
         "Double-strain into a chilled coupe.",
         "Dust the foam with chilli salt."])

S("Toreador", UK, LDN, "rare", "20-22%",
  "Tequila with apricot brandy and lime. One of the first tequila drinks to reach a London bar book.",
  ["apricot", "agave", "lime"],
  ["Tequila", "Apricot brandy", "Lime juice"],
  "Tequila barely appears in English cocktail books before the 1930s, and when it does it is usually spelled wrong and described as a Mexican brandy.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Apricot brandy", "0.75 oz / 22 ml"),
   ("Lime juice", "0.5 oz / 15 ml"), ("Ice", "cubed")],
  "A lime wheel")

S("Matador", US, "California, USA", "uncommon", "12-14%",
  "Tequila, pineapple and lime. The easiest agave drink there is, and Trader Vic's answer to the Margarita.",
  ["pineapple", "agave", "lime"],
  ["Tequila", "Pineapple juice", "Lime juice"],
  "Pineapple and agave share a green, faintly vegetal note, which is why the pairing works far better than the fruit-juice shortcut it looks like.",
  [("Blanco tequila", "1.5 oz / 45 ml"), ("Pineapple juice", "3 oz / 90 ml"),
   ("Lime juice", "0.5 oz / 15 ml"), ("Ice", "cubed")],
  "A pineapple wedge", glass="Rocks glass")

B("Brave Bull", US, "California, USA", "Spirit-Forward", "uncommon", "28-30%",
  "Tequila and coffee liqueur over ice. A Black Russian with agave instead of vodka.",
  ["coffee", "agave", "chocolate"], "Rocks glass",
  ["Tequila", "Coffee liqueur"],
  "Swap the tequila for vodka and it is a Black Russian; swap it for bourbon and it has no name at all, which is a fair comment on how these drinks get named.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Coffee liqueur", "1 oz / 30 ml"),
   ("Ice", "cubed")],
  ["Fill a rocks glass with ice.",
   "Add the tequila and the coffee liqueur.",
   "Stir briefly to combine and chill.",
   "Twist a strip of lemon peel over the top and drop it in."],
  "A lemon twist")

S("Chapala", US, "California, USA", "rare", "16-18%",
  "Tequila with orange, lime, grenadine and a drop of orange flower water. Named for Mexico's largest lake.",
  ["orange blossom", "orange", "lime", "agave"],
  ["Tequila", "Orange juice", "Lime juice", "Orange flower water"],
  "Orange flower water is measured in drops and turns up in only a handful of classics — this one, the Ramos Gin Fizz, and almost nothing else.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Orange juice", "1 oz / 30 ml"),
   ("Lime juice", "0.5 oz / 15 ml"), ("Grenadine", "0.5 oz / 15 ml"),
   ("Orange flower water", "2 drops"), ("Ice", "cubed")],
  "An orange twist", glass="Rocks glass")

S("Berta's Special", MX, "Taxco, Mexico", "rare", "16-18%",
  "Tequila, honey, lime and soda with an egg white. From a Taxco cantina that has been open since the 1930s.",
  ["honey", "lime", "agave", "bitters"],
  ["Tequila", "Honey", "Lime juice", "Soda water"],
  "Bertita's still stands on the square in Taxco, and the drink is one of very few pre-war Mexican cocktails whose bar of origin is still trading.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Honey syrup", "0.75 oz / 22 ml"),
   ("Lime juice", "0.75 oz / 22 ml"), ("Egg white", "1"),
   ("Angostura bitters", "3 dashes"), ("Soda water", "2 oz / 90 ml, to top"),
   ("Ice", "cubed")],
  "A lime wheel", sub="Fizz", glass="Highball glass",
  steps=["Dry-shake the tequila, honey, lime, egg white and bitters without ice.",
         "Add ice and shake hard until cold.",
         "Strain into a tall glass over fresh ice.",
         "Top with soda water and stir once."])

S("Picador", UK, LDN, "rare", "24-26%",
  "Tequila, Cointreau and lime, shaken and served up with no salt. The Margarita as a London bar first wrote it down.",
  ["agave", "orange", "lime"],
  ["Tequila", "Cointreau", "Lime juice"],
  "It appears in British books in the 1930s under this name, which puts a Margarita in print in London before the drink had settled on its Spanish one.",
  [("Blanco tequila", "2 oz / 60 ml"), ("Cointreau", "1 oz / 30 ml"),
   ("Lime juice", "0.75 oz / 22 ml"), ("Ice", "cubed")],
  "A lime twist")

S("Cadillac Margarita", US, "California, USA", "uncommon", "24-26%",
  "A Margarita made with reposado and finished with a float of Grand Marnier poured over the back of a spoon.",
  ["orange", "agave", "oak", "lime"],
  ["Reposado tequila", "Cointreau", "Lime juice", "Grand Marnier"],
  "The float is the whole point — stirred in it disappears, but sitting on top the Grand Marnier hits first and the tequila arrives underneath it.",
  [("Reposado tequila", "2 oz / 60 ml"), ("Cointreau", "0.5 oz / 15 ml"),
   ("Lime juice", "0.75 oz / 22 ml"), ("Agave syrup", "0.25 oz / 7 ml"),
   ("Grand Marnier", "0.5 oz / 15 ml, to float"), ("Ice", "cubed")],
  "A lime wheel and a salted rim",
  glass="Rocks glass with a salted half-rim",
  steps=["Salt half the rim of a rocks glass, so the drinker can choose.",
         "Shake the tequila, Cointreau, lime and agave with ice.",
         "Strain into the glass over one large cube.",
         "Float the Grand Marnier over the back of a barspoon."])

B("Changuirongo", MX, "Jalisco, Mexico", "Highball", "uncommon", "8-10%",
  "Tequila and whatever soda is cold. Mexico's everyday highball, and deliberately unfussy.",
  ["agave", "citrus", "soda"], "Highball glass",
  ["Tequila", "Soda"],
  "Grapefruit soda makes it a Paloma and cola makes it a Charro Negro; with anything else it just keeps this name and nobody minds.",
  [("Blanco tequila", "2 oz / 60 ml"),
   ("Lemon-lime or grapefruit soda", "5 oz / 150 ml"),
   ("Lime", "1 wedge"), ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the tequila.",
   "Top with whatever cold soda is to hand.",
   "Squeeze a lime wedge in and drop it in the glass."],
  "A lime wedge")
