# -*- coding: utf-8 -*-
"""The world's non-alcoholic drinks that belong to bar and cantina culture.

Scope call: the mocktail canon plus the traditional refreshers people order
INSTEAD of a drink. Deliberately excludes coffee-shop and tea-shop drinks —
a flat white is a real drink and does not belong in a cocktail dex.
"""
from ck import S, B, C

US, UK, MX = "USA", "United Kingdom", "Mexico"

# =================================================== THE MOCKTAIL CANON

B("Shirley Temple", US, "California, USA", "Party", "common", "0%",
  "Ginger ale with grenadine and a cherry. The first drink most people are ever served in a glass that looks grown up.",
  ["ginger", "pomegranate", "cherry"], "Highball glass",
  ["Ginger ale", "Grenadine", "Maraschino cherry"],
  "Shirley Temple herself disliked it and said so repeatedly, calling it too sweet, and never received a cent from the restaurants that sold it.",
  [("Ginger ale", "6 oz / 180 ml"), ("Grenadine", "0.5 oz / 15 ml"),
   ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the ginger ale.",
   "Pour the grenadine down the inside of the glass so it settles at the bottom.",
   "Drop in a cherry and serve without stirring."],
  "A maraschino cherry")

B("Roy Rogers", US, "California, USA", "Party", "uncommon", "0%",
  "Cola with grenadine and a cherry. The Shirley Temple for whoever did not want the ginger ale.",
  ["cola", "pomegranate", "cherry"], "Highball glass",
  ["Cola", "Grenadine", "Maraschino cherry"],
  "The pair were named for two film stars of the same era and served side by side, which made ordering one of them a small declaration of taste.",
  [("Cola", "6 oz / 180 ml"), ("Grenadine", "0.5 oz / 15 ml"),
   ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Add the cola.",
   "Pour the grenadine slowly down the side.",
   "Drop in a cherry and serve."],
  "A maraschino cherry")

B("Arnold Palmer", US, "California, USA", "Party", "common", "0%",
  "Iced tea and lemonade, half and half. Named for a golfer who ordered it so often that bar staff learned the ratio.",
  ["black tea", "lemon", "sugar"], "Highball glass",
  ["Iced tea", "Lemonade"],
  "Palmer ordered it at a Palm Springs restaurant loudly enough that a woman at the next table asked for the same, and the name stuck that afternoon.",
  [("Cold unsweetened iced tea", "5 oz / 150 ml"),
   ("Lemonade", "5 oz / 150 ml"), ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Pour the iced tea and lemonade in together.",
   "Stir once to combine.",
   "Hang a lemon wheel on the rim."],
  "A lemon wheel")

B("Virgin Mary", US, "New York City, USA", "Brunch", "common", "0%",
  "A Bloody Mary with the vodka left out, which changes almost nothing about how it is made.",
  ["tomato", "horseradish", "celery", "pepper"], "Highball glass",
  ["Tomato juice", "Lemon juice", "Worcestershire sauce", "Horseradish"],
  "The seasoning does all the work in a Bloody Mary, which is why the alcohol-free version is one of the very few that loses nothing at all.",
  [("Tomato juice", "5 oz / 150 ml"), ("Lemon juice", "0.5 oz / 15 ml"),
   ("Worcestershire sauce", "4 dashes"), ("Hot sauce", "3 dashes"),
   ("Horseradish", "0.5 tsp"), ("Celery salt", "a pinch"),
   ("Black pepper", "a pinch"), ("Ice", "cubed")],
  ["Combine everything but the ice and roll it between two tins to mix without foaming.",
   "Pour into a tall glass over fresh ice.",
   "Season the top with more celery salt and cracked pepper.",
   "Garnish with a celery stick and a lemon wedge."],
  "A celery stick and a lemon wedge")

S("Cinderella", UK, "London, England", "uncommon", "0%",
  "Pineapple, orange and lemon shaken hard and topped with soda. The Savoy's own alcohol-free drink.",
  ["pineapple", "orange", "lemon"],
  ["Pineapple juice", "Orange juice", "Lemon juice", "Soda water"],
  "The Savoy Cocktail Book prints a short run of temperance drinks alongside 750 alcoholic ones, and this is the only one that has stayed in print.",
  [("Pineapple juice", "1 oz / 30 ml"), ("Orange juice", "1 oz / 30 ml"),
   ("Lemon juice", "1 oz / 30 ml"), ("Grenadine", "1 dash"),
   ("Soda water", "2 oz / 60 ml, to top"), ("Ice", "cubed")],
  "An orange slice and a cherry",
  sub="Fizz", glass="Highball glass",
  steps=["Shake the three juices and the grenadine hard with ice.",
         "Strain into a tall glass over fresh ice.",
         "Top with soda water.",
         "Garnish with orange and a cherry."])

B("Egg Cream", US, "Brooklyn, USA", "Retro", "uncommon", "0%",
  "Milk, seltzer and chocolate syrup, containing neither egg nor cream. The Brooklyn candy-store drink.",
  ["chocolate", "milk", "soda"], "Soda glass",
  ["Milk", "Seltzer", "Chocolate syrup"],
  "The name has never been explained convincingly; the drink has no egg and no cream, and Brooklyn has been arguing about why for a hundred years.",
  [("Whole milk", "2 oz / 60 ml"), ("Chocolate syrup", "1 oz / 30 ml"),
   ("Cold seltzer", "6 oz / 180 ml")],
  ["Pour the milk into a tall glass.",
   "Spray the seltzer in hard, straight down, to raise a thick white head.",
   "Slide the chocolate syrup down the inside of the glass under the foam.",
   "Stir the bottom only, leaving the white head intact, and drink it immediately."],
  "None — the white head is the drink")

B("Italian Soda", US, "California, USA", "Party", "common", "0%",
  "Flavoured syrup, soda water and ice. Add cream and it becomes a French soda, which is the only difference.",
  ["berry", "soda", "vanilla"], "Highball glass",
  ["Flavoured syrup", "Soda water"],
  "It is not Italian — the name came from American coffee bars in the 1980s selling Italian-branded syrups, and no bar in Italy calls it that.",
  [("Fruit syrup", "1 oz / 30 ml"), ("Soda water", "7 oz / 210 ml"),
   ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Pour the syrup over the ice.",
   "Top with cold soda water.",
   "Stir once, or float a spoon of cream on top to make it a French soda."],
  "A lemon wheel")

# ============================================== THE AMERICAS

B("Agua de Jamaica", MX, "Mexico", "Regional", "common", "0%",
  "Dried hibiscus steeped and sweetened, served ice cold. Deep red, sharply tart, and sold on every Mexican corner.",
  ["hibiscus", "cranberry", "citrus"], "Tall glass",
  ["Hibiscus flowers", "Sugar", "Water"],
  "The flowers are calyces rather than petals, and the same plant travels the world under different names — sorrel in the Caribbean, karkade in Egypt, bissap in Senegal.",
  [("Dried hibiscus", "1 cup"), ("Water", "8 cups"),
   ("Sugar", "1 cup"), ("Lime", "1, juiced"), ("Ice", "cubed")],
  ["Boil half the water and pour it over the hibiscus. Steep for 20 minutes.",
   "Strain, pressing the flowers, and stir in the sugar until dissolved.",
   "Add the remaining cold water and the lime juice.",
   "Chill thoroughly and serve over plenty of ice."],
  "A lime wheel")

B("Horchata", MX, "Mexico", "Regional", "common", "0%",
  "Rice steeped with cinnamon, blended and strained into a cold sweet white drink.",
  ["rice", "cinnamon", "vanilla"], "Tall glass",
  ["Rice", "Cinnamon", "Sugar", "Milk"],
  "Spain's original is made from tigernuts rather than rice — horchata de chufa — and the two versions share a name, a colour and almost nothing else.",
  [("Long-grain rice", "1 cup"), ("Water", "4 cups"),
   ("Cinnamon sticks", "2"), ("Sugar", "0.75 cup"),
   ("Whole milk", "1 cup"), ("Vanilla extract", "1 tsp"), ("Ice", "cubed")],
  ["Soak the rice and cinnamon in the water overnight.",
   "Blend the whole lot until the rice breaks down completely.",
   "Strain twice through a fine cloth until no grit remains.",
   "Stir in the milk, sugar and vanilla, chill hard and serve over ice."],
  "Ground cinnamon")

B("Tamarindo", MX, "Mexico", "Regional", "uncommon", "0%",
  "Tamarind pulp, sugar and water. Sour, brown and far more refreshing than it looks.",
  ["tamarind", "brown sugar", "sour"], "Tall glass",
  ["Tamarind", "Sugar", "Water"],
  "Tamarind reached Mexico from Asia by way of the Manila galleons, and stayed so thoroughly that it now reads as a Mexican flavour rather than an imported one.",
  [("Tamarind pods", "12, or 4 oz pulp"), ("Water", "6 cups"),
   ("Sugar", "0.75 cup"), ("Ice", "cubed")],
  ["Shell the pods and simmer the pulp in half the water until it softens.",
   "Mash and push it through a sieve, discarding the seeds and fibres.",
   "Stir in the sugar and the remaining cold water.",
   "Chill and serve over ice with a pinch of salt if you like it sharper."],
  "A lime wedge")

C("Atole", MX, "Mexico", "Hot", "uncommon", "0%",
  "Masa cooked into hot milk with cinnamon and sugar. Thick enough to be breakfast, and drunk from a mug.",
  ["corn", "cinnamon", "vanilla"], "Mug",
  ["Masa harina", "Milk", "Cinnamon", "Piloncillo"],
  "Atole predates the Spanish arrival by centuries and is one of very few pre-Columbian drinks still made the same way in the same country.",
  [("Masa harina", "0.5 cup"), ("Water", "2 cups"),
   ("Whole milk", "2 cups"), ("Piloncillo or brown sugar", "4 oz / 110 g"),
   ("Cinnamon stick", "1"), ("Vanilla extract", "1 tsp")],
  ["Whisk the masa into the cold water until completely smooth with no lumps.",
   "Heat the milk with the cinnamon and piloncillo until the sugar dissolves.",
   "Pour in the masa mixture in a steady stream, whisking constantly.",
   "Simmer gently for ten minutes, stirring, until it thickens. Add the vanilla and serve hot."],
  "A cinnamon stick", "boiled")

C("Champurrado", MX, "Mexico", "Hot", "uncommon", "0%",
  "Atole with Mexican chocolate whisked through it. Thicker, darker, and the one that goes with tamales.",
  ["chocolate", "corn", "cinnamon"], "Mug",
  ["Masa harina", "Mexican chocolate", "Milk", "Piloncillo"],
  "Mexican drinking chocolate is deliberately gritty — the sugar is coarse and unrefined, and the texture is the point rather than a flaw to be smoothed out.",
  [("Masa harina", "0.5 cup"), ("Water", "2 cups"),
   ("Whole milk", "2 cups"), ("Mexican chocolate", "3 oz / 85 g"),
   ("Piloncillo", "3 oz / 85 g"), ("Cinnamon stick", "1")],
  ["Whisk the masa into the cold water until smooth.",
   "Heat the milk with the chocolate, piloncillo and cinnamon until melted.",
   "Whisk hard with a molinillo or a balloon whisk until it foams.",
   "Stir in the masa mixture and simmer, stirring, until thick. Serve very hot."],
  "None", "boiled")

C("Ponche Navideño", MX, "Mexico", "Hot", "uncommon", "0%",
  "Hot fruit punch with tejocotes, guava, sugarcane and hibiscus. Mexican Christmas in a clay mug.",
  ["guava", "tamarind", "cinnamon", "hibiscus"], "Clay mug",
  ["Tejocote", "Guava", "Sugarcane", "Piloncillo"],
  "The fruit is meant to be eaten out of the bottom of the mug with a spoon, which is why it is served in a wide clay jarrito rather than a glass.",
  [("Water", "4 quarts"), ("Tejocotes", "10, halved"),
   ("Guavas", "4, quartered"), ("Sugarcane", "1 stick, in batons"),
   ("Prunes", "10"), ("Piloncillo", "8 oz / 225 g"),
   ("Cinnamon sticks", "3"), ("Dried hibiscus", "2 tbsp")],
  ["Simmer the water with the piloncillo, cinnamon and sugarcane for 20 minutes.",
   "Add the tejocotes and prunes and simmer another 20 minutes until soft.",
   "Add the guava and hibiscus and simmer for a final 15 minutes.",
   "Ladle into clay mugs, making sure each one gets fruit, and serve very hot."],
  "The fruit itself, in the bottom of the mug", "boiled")

B("Morir Soñando", "Dominican Republic", "Dominican Republic", "Regional", "uncommon", "0%",
  "Orange juice and cold milk beaten together with sugar and ice. The name means to die dreaming.",
  ["orange", "milk", "vanilla"], "Tall glass",
  ["Orange juice", "Evaporated milk", "Sugar"],
  "Everything has to be properly cold before it meets — warm juice curdles the milk instantly, and the whole technique is about avoiding that.",
  [("Evaporated milk", "4 oz / 120 ml"), ("Sugar", "2 tbsp"),
   ("Orange juice", "4 oz / 120 ml, very cold"), ("Ice", "1 cup")],
  ["Stir the sugar into the cold milk until fully dissolved.",
   "Fill a tall glass with ice and pour the milk over it to chill it further.",
   "Add the cold orange juice in a slow stream while stirring constantly.",
   "Serve at once, before it has any chance to separate."],
  "An orange wheel")

B("Chicha Morada", "Peru", "Peru", "Regional", "uncommon", "0%",
  "Purple corn boiled with pineapple, apple and spice, then cooled and sharpened with lime.",
  ["purple corn", "pineapple", "clove", "lime"], "Tall glass",
  ["Purple corn", "Pineapple", "Cloves", "Lime"],
  "Peruvian purple corn is one of the most anthocyanin-rich foods known, which is why the drink comes out an almost unnatural violet.",
  [("Dried purple corn", "1 lb / 450 g"), ("Water", "4 quarts"),
   ("Pineapple rind", "from 1 pineapple"), ("Apple", "1, quartered"),
   ("Cloves", "6"), ("Cinnamon sticks", "2"),
   ("Sugar", "1 cup"), ("Lime juice", "3 oz / 90 ml")],
  ["Boil the corn with the pineapple rind, apple, cloves and cinnamon for 45 minutes.",
   "Strain and discard the solids.",
   "Stir in the sugar while the liquid is still warm.",
   "Cool completely, then add the lime juice and serve over ice with diced apple."],
  "Diced apple and a lime wheel")

B("Mauby", "Barbados", "Barbados", "Regional", "rare", "0%",
  "Mauby bark boiled with spice and sweetened. Bitter in a way no other soft drink is, and drunk for exactly that.",
  ["bitter bark", "aniseed", "cinnamon"], "Tall glass",
  ["Mauby bark", "Sugar", "Cinnamon", "Aniseed"],
  "The bitterness comes from the bark of Colubrina elliptica and lingers long after swallowing — Barbadians describe acquiring the taste as a rite of passage.",
  [("Mauby bark", "2 oz / 55 g"), ("Water", "6 cups"),
   ("Cinnamon sticks", "2"), ("Aniseed", "1 tsp"),
   ("Cloves", "6"), ("Sugar", "1.5 cups")],
  ["Boil the bark with the spices in the water for 30 minutes.",
   "Strain and stir in the sugar while hot.",
   "Cool completely — it turns more bitter as it cools, which is expected.",
   "Dilute to taste with cold water and serve over plenty of ice."],
  "None")

C("Colada Morada", "Ecuador", "Ecuador", "Hot", "rare", "0%",
  "Purple corn flour cooked with berries, spice and herbs. Ecuador drinks it once a year, for the dead.",
  ["blackberry", "purple corn", "clove", "allspice"], "Mug",
  ["Purple corn flour", "Blackberries", "Blackcurrant", "Spices"],
  "It is served on the second of November with guaguas de pan — bread shaped as swaddled infants — and the pairing is not optional.",
  [("Purple corn flour", "1 cup"), ("Water", "6 cups"),
   ("Blackberries", "2 cups"), ("Blackcurrants", "1 cup"),
   ("Pineapple", "1 cup, diced"), ("Panela", "8 oz / 225 g"),
   ("Cinnamon sticks", "2"), ("Cloves", "6"),
   ("Lemongrass", "2 stalks"), ("Allspice berries", "6")],
  ["Simmer the water with the panela, spices and lemongrass for 30 minutes, then strain.",
   "Blend and sieve the berries, and add the purée to the spiced liquid.",
   "Whisk the corn flour into a little cold water and stir it in.",
   "Simmer, stirring constantly, until it thickens. Add the pineapple at the end and serve hot."],
  "Diced fruit", "boiled")

# ================================================ MIDDLE EAST & LEVANT

B("Ayran", "Turkey", "Turkey", "Regional", "common", "0%",
  "Yoghurt whisked with cold water and salt. Savoury rather than sweet, and drunk with grilled meat.",
  ["yoghurt", "salt", "sour"], "Tall glass",
  ["Yoghurt", "Water", "Salt"],
  "Turkey sells more ayran than cola, and it is the drink poured alongside kebab everywhere from roadside grills to the state airline.",
  [("Plain yoghurt", "6 oz / 180 ml"), ("Cold water", "4 oz / 120 ml"),
   ("Salt", "0.25 tsp"), ("Ice", "cubed")],
  ["Whisk the yoghurt and salt together until completely smooth.",
   "Add the cold water in a stream, whisking, until it is drinkable and slightly frothy.",
   "Pour over ice.",
   "Serve at once, before the froth falls."],
  "A dried mint dusting, in some regions")

B("Doogh", "Iran", "Iran", "Regional", "uncommon", "0%",
  "Yoghurt thinned with sparkling water and seasoned with dried mint. Ayran's sharper Persian cousin.",
  ["yoghurt", "mint", "salt"], "Tall glass",
  ["Yoghurt", "Sparkling water", "Dried mint", "Salt"],
  "The carbonation is the difference — Persian doogh is traditionally naturally fizzy from a brief fermentation, which soda water now imitates.",
  [("Plain yoghurt", "5 oz / 150 ml"), ("Sparkling water", "5 oz / 150 ml"),
   ("Dried mint", "0.5 tsp"), ("Salt", "0.25 tsp"), ("Ice", "cubed")],
  ["Whisk the yoghurt, salt and dried mint until smooth.",
   "Add the sparkling water slowly so it keeps its bubble.",
   "Pour over ice without stirring hard.",
   "Dust with more dried mint and serve."],
  "Dried mint and a cucumber slice")

B("Sekanjabin", "Iran", "Iran", "Regional", "rare", "0%",
  "Mint and vinegar syrup diluted with cold water. Sweet and sour at once, and a thousand years old.",
  ["mint", "vinegar", "honey"], "Tall glass",
  ["Vinegar", "Sugar", "Mint", "Water"],
  "It is the ancestor of the shrub — the drinking-vinegar tradition reached Europe through Persian and Arab medicine, and the word sherbet comes along the same route.",
  [("Sugar", "2 cups"), ("Water", "2 cups"),
   ("White wine vinegar", "0.5 cup"), ("Fresh mint", "1 large bunch"),
   ("Cold water", "to dilute"), ("Ice", "cubed")],
  ["Simmer the sugar and water until it forms a light syrup.",
   "Add the vinegar and simmer for another 15 minutes.",
   "Take it off the heat, drop in the mint, and leave to steep until cool. Strain and bottle.",
   "To serve, dilute one part syrup to five parts cold water, over ice, with grated cucumber."],
  "Grated cucumber and a mint sprig")

B("Jallab", "Lebanon", "Lebanon", "Regional", "rare", "0%",
  "Date and grape molasses with rose water, poured over crushed ice and topped with pine nuts and raisins.",
  ["date", "rose", "pine nut", "smoke"], "Tall glass",
  ["Date molasses", "Grape molasses", "Rose water", "Pine nuts"],
  "The syrup is traditionally smoked with Arabic incense before bottling, which is where the faint resinous note underneath the sweetness comes from.",
  [("Jallab syrup", "1.5 oz / 45 ml"), ("Cold water", "6 oz / 180 ml"),
   ("Rose water", "0.25 tsp"), ("Pine nuts", "1 tbsp"),
   ("Golden raisins", "1 tbsp"), ("Ice", "crushed")],
  ["Soak the pine nuts and raisins in cold water for an hour so they soften and float.",
   "Stir the syrup and rose water into the cold water until fully combined.",
   "Fill a tall glass with crushed ice and pour the mixture over.",
   "Spoon the soaked pine nuts and raisins on top."],
  "Pine nuts and golden raisins")

C("Salep", "Turkey", "Turkey", "Hot", "rare", "0%",
  "Hot milk thickened with orchid tuber flour and dusted with cinnamon. Drunk from a cup on winter streets in Istanbul.",
  ["orchid", "cinnamon", "milk"], "Cup",
  ["Salep flour", "Milk", "Sugar", "Cinnamon"],
  "Real salep flour is milled from wild orchid tubers, and harvesting has been restricted for decades — most street salep today is a starch blend by necessity.",
  [("Whole milk", "16 oz / 500 ml"), ("Salep flour", "1 tbsp"),
   ("Sugar", "3 tbsp"), ("Cinnamon", "to dust")],
  ["Whisk the salep flour and sugar into the cold milk before any heat goes near it.",
   "Heat slowly, whisking constantly, so it thickens without catching.",
   "Simmer for five minutes until it coats the back of a spoon.",
   "Pour into cups and dust heavily with cinnamon."],
  "Ground cinnamon", "boiled")

C("Boza", "Turkey", "Turkey", "Regional", "rare", "0-1%",
  "Fermented millet, thick and faintly sour, served cold with cinnamon and roasted chickpeas.",
  ["millet", "sour", "cinnamon"], "Cup",
  ["Millet", "Sugar", "Cinnamon", "Roasted chickpeas"],
  "Vefa Bozacısı has sold it from the same Istanbul shop since 1876, and still keeps the glass Atatürk drank from on display.",
  [("Bulgur or millet", "1 cup"), ("Water", "6 cups"),
   ("Sugar", "1 cup"), ("Active starter or yeast", "1 tsp"),
   ("Cinnamon", "to dust"), ("Roasted chickpeas", "to serve")],
  ["Boil the grain in the water until it collapses completely, then blend and sieve it smooth.",
   "Stir in the sugar and cool to room temperature.",
   "Add the starter and leave, covered, for a day or two until it turns faintly sour and fizzy.",
   "Chill and serve in cups, dusted with cinnamon and scattered with roasted chickpeas."],
  "Cinnamon and roasted chickpeas", "infused")

# =========================================================== SOUTH ASIA

B("Lassi", "India", "Punjab, India", "Regional", "common", "0%",
  "Yoghurt blended with water and sugar until frothy. The sweet version of a drink that is just as often salted.",
  ["yoghurt", "cardamom", "sugar"], "Tall glass",
  ["Yoghurt", "Water", "Sugar", "Cardamom"],
  "Salted lassi came first and remains the everyday one across much of northern India; sweet lassi is the version that travelled.",
  [("Plain yoghurt", "1 cup"), ("Cold water", "0.5 cup"),
   ("Sugar", "2 tbsp"), ("Ground cardamom", "a pinch"),
   ("Ice", "cubed")],
  ["Blend the yoghurt, water and sugar until light and frothy.",
   "Add the cardamom and blend again briefly.",
   "Pour over ice into a tall glass.",
   "Top with a spoon of the froth from the blender."],
  "Ground cardamom and a pistachio dusting")

B("Mango Lassi", "India", "Punjab, India", "Regional", "common", "0%",
  "Lassi made with ripe mango pulp. Thicker, sweeter, and the version most of the world met first.",
  ["mango", "yoghurt", "cardamom"], "Tall glass",
  ["Mango", "Yoghurt", "Sugar", "Cardamom"],
  "Alphonso mangoes are the ones worth using and are in season for barely two months, which is why tinned Alphonso pulp is a legitimate ingredient rather than a compromise.",
  [("Ripe mango pulp", "1 cup"), ("Plain yoghurt", "1 cup"),
   ("Cold milk", "0.25 cup"), ("Sugar", "1 tbsp"),
   ("Ground cardamom", "a pinch"), ("Ice", "cubed")],
  ["Blend the mango, yoghurt, milk and sugar until completely smooth.",
   "Taste and add sugar only if the mango needs it.",
   "Pour over ice.",
   "Dust with cardamom and chopped pistachio."],
  "Chopped pistachio and cardamom")

C("Falooda", "India", "Mumbai, India", "Creamy & Dessert", "uncommon", "0%",
  "Rose syrup, milk, vermicelli, basil seeds and ice cream in one tall glass. Drink and dessert at once.",
  ["rose", "vanilla", "milk", "basil seed"], "Tall glass",
  ["Rose syrup", "Milk", "Vermicelli", "Basil seeds"],
  "Basil seeds swell into translucent jelly in water within minutes, and that texture — not the flavour, which is negligible — is the entire reason they are in the glass.",
  [("Rose syrup", "2 tbsp"), ("Cold milk", "6 oz / 180 ml"),
   ("Cooked falooda vermicelli", "3 tbsp"), ("Basil seeds", "1 tbsp, soaked"),
   ("Vanilla ice cream", "1 scoop"), ("Chopped nuts", "1 tbsp")],
  ["Soak the basil seeds in water for 20 minutes until they swell and turn translucent.",
   "Spoon the rose syrup into the bottom of a tall glass, then the vermicelli and basil seeds.",
   "Pour the cold milk over slowly so the layers stay visible.",
   "Top with a scoop of ice cream and scatter chopped nuts over it."],
  "Chopped pistachio and a rose petal", "built")

# ============================================================ EAST ASIA

B("Teh Tarik", "Malaysia", "Malaysia", "Regional", "common", "0%",
  "Strong tea and condensed milk poured between two vessels from arm's length until it foams.",
  ["black tea", "condensed milk", "caramel"], "Glass mug",
  ["Black tea", "Condensed milk"],
  "Tarik means pulled — the long pour aerates the tea and cools it, and the height of the pull is a genuine point of pride among stall owners.",
  [("Strong black tea", "6 oz / 180 ml"), ("Sweetened condensed milk", "2 tbsp"),
   ("Evaporated milk", "1 tbsp")],
  ["Brew the tea strong and strain it.",
   "Stir in the condensed and evaporated milk until dissolved.",
   "Pour it back and forth between two jugs, pulling the stream as far apart as you dare.",
   "Stop when a thick head of foam has built, and serve immediately."],
  "The foam itself")

C("Cendol", "Indonesia", "Java, Indonesia", "Creamy & Dessert", "uncommon", "0%",
  "Green rice-flour jellies in coconut milk and palm sugar syrup over shaved ice.",
  ["pandan", "coconut", "palm sugar"], "Bowl or tall glass",
  ["Rice flour jelly", "Coconut milk", "Palm sugar", "Pandan"],
  "The green comes from pandan leaf rather than food colouring, and the jellies are pressed through a perforated mould straight into iced water to set.",
  [("Cendol jellies", "0.5 cup"), ("Coconut milk", "4 oz / 120 ml"),
   ("Gula melaka syrup", "2 tbsp"), ("Shaved ice", "1 cup"),
   ("Salt", "a pinch")],
  ["Pile shaved ice into a bowl or a wide glass.",
   "Spoon the green cendol jellies over the ice.",
   "Pour the salted coconut milk over the top.",
   "Finish with a heavy drizzle of palm sugar syrup and stir before eating."],
  "A drizzle of palm sugar syrup", "built")

B("Es Kelapa Muda", "Indonesia", "Indonesia", "Regional", "uncommon", "0%",
  "Young coconut water and its soft flesh over ice with palm sugar. Served in the shell it came out of.",
  ["coconut", "palm sugar", "lime"], "Coconut shell",
  ["Young coconut", "Palm sugar", "Ice"],
  "The flesh of a young coconut is soft enough to scrape out with a spoon and is nothing like the hard white meat of a mature one.",
  [("Young coconut", "1"), ("Palm sugar syrup", "1 tbsp"),
   ("Lime juice", "1 tsp"), ("Ice", "cubed")],
  ["Open the coconut at the top and pour the water into a jug.",
   "Scrape the soft flesh out in strips with a spoon.",
   "Stir the palm sugar syrup and lime into the water.",
   "Return everything to the shell with ice, and serve with a spoon and a straw."],
  "The coconut flesh itself")

B("Nam Manao", "Thailand", "Thailand", "Regional", "common", "0%",
  "Lime juice, sugar and salt over crushed ice. Three ingredients and the salt is not optional.",
  ["lime", "salt", "sugar"], "Tall glass",
  ["Lime juice", "Sugar", "Salt"],
  "The pinch of salt is what makes it Thai — it flattens the sharp edge of the lime and makes the drink read as balanced rather than sour.",
  [("Lime juice", "1.5 oz / 45 ml"), ("Simple syrup", "1 oz / 30 ml"),
   ("Cold water", "4 oz / 120 ml"), ("Salt", "a pinch"),
   ("Ice", "crushed")],
  ["Stir the lime juice, syrup and salt together until the salt dissolves.",
   "Add the cold water.",
   "Fill a tall glass with crushed ice and pour over.",
   "Stir once and taste — it should be sour first, then sweet, then faintly salty."],
  "A lime wheel")

B("Suanmeitang", "China", "Beijing, China", "Regional", "uncommon", "0%",
  "Smoked sour plums boiled with hawthorn and osmanthus. Dark, tart and drunk cold all summer.",
  ["smoked plum", "hawthorn", "osmanthus"], "Tall glass",
  ["Smoked sour plum", "Hawthorn", "Osmanthus", "Rock sugar"],
  "It was an imperial court drink under the Qing, and Beijing families still boil a pot at the start of summer and keep it in the fridge until autumn.",
  [("Smoked sour plums", "8"), ("Dried hawthorn slices", "1 oz / 30 g"),
   ("Liquorice root", "2 slices"), ("Water", "8 cups"),
   ("Rock sugar", "4 oz / 110 g"), ("Dried osmanthus", "1 tsp")],
  ["Rinse the plums and hawthorn and soak them for an hour.",
   "Boil everything but the osmanthus and sugar for 45 minutes.",
   "Add the rock sugar and osmanthus and simmer for a final five minutes.",
   "Strain, cool completely and serve very cold over ice."],
  "A few osmanthus flowers")

C("Sujeonggwa", "South Korea", "South Korea", "Regional", "uncommon", "0%",
  "Cinnamon and ginger boiled separately then combined, sweetened, and served cold with persimmon and pine nuts.",
  ["cinnamon", "ginger", "persimmon"], "Small bowl",
  ["Cinnamon", "Ginger", "Honey", "Dried persimmon"],
  "The cinnamon and ginger are boiled in separate pots and only combined at the end, because cooking them together muddies both.",
  [("Cinnamon sticks", "2 oz / 55 g"), ("Fresh ginger", "2 oz / 55 g, sliced"),
   ("Water", "8 cups, split"), ("Brown sugar", "1 cup"),
   ("Dried persimmons", "4"), ("Pine nuts", "1 tbsp")],
  ["Boil the cinnamon in half the water and the ginger in the other half, separately, for 40 minutes each.",
   "Strain both and combine, then stir in the sugar and simmer until dissolved.",
   "Cool completely and refrigerate overnight.",
   "Serve very cold with a soaked dried persimmon and a few pine nuts floating on top."],
  "Dried persimmon and pine nuts", "boiled")

B("Sikhye", "South Korea", "South Korea", "Regional", "rare", "0%",
  "Sweet rice punch with the grains left floating. Malted, faintly grainy and served ice cold after a meal.",
  ["malt", "rice", "ginger"], "Small bowl",
  ["Malted barley", "Cooked rice", "Sugar"],
  "The malt enzymes convert the rice starch to sugar — the same process that starts a beer, halted before any fermentation can begin.",
  [("Malted barley powder", "1 cup"), ("Water", "10 cups"),
   ("Cooked short-grain rice", "2 cups"), ("Sugar", "1 cup"),
   ("Fresh ginger", "3 slices"), ("Pine nuts", "1 tbsp")],
  ["Steep the malt powder in the water for an hour, then strain and keep the clear liquid.",
   "Add the cooked rice and hold at 60C for four to five hours until the grains float.",
   "Skim off the floating rice and reserve it, then boil the liquid with the sugar and ginger.",
   "Cool completely and serve very cold with a spoonful of the reserved rice and a few pine nuts."],
  "Floating rice grains and pine nuts")

C("Amazake", "Japan", "Japan", "Hot", "uncommon", "0-1%",
  "Rice fermented with koji into a thick sweet drink. No sugar is added and none is needed.",
  ["rice", "koji", "sweet"], "Small cup",
  ["Rice", "Koji", "Water"],
  "All the sweetness comes from koji enzymes breaking rice starch into glucose — the same mould that starts sake, stopped before yeast is ever introduced.",
  [("Cooked short-grain rice", "2 cups"), ("Dried rice koji", "1 cup"),
   ("Water", "2 cups"), ("Fresh ginger", "to grate")],
  ["Cool the cooked rice to about 60C and stir the koji and water through it.",
   "Hold it at 55 to 60C for eight to ten hours, stirring occasionally.",
   "Taste — it is done when it is properly sweet with no starchiness left.",
   "Thin with hot water to drink, and serve with a little grated ginger."],
  "Grated ginger", "infused")

B("Calpis", "Japan", "Tokyo, Japan", "Regional", "uncommon", "0%",
  "Cultured milk concentrate diluted with cold water. Tart, milky and unlike anything outside Japan.",
  ["yoghurt", "citrus", "milk"], "Tall glass",
  ["Calpis concentrate", "Water"],
  "It has been made since 1919 and is sold abroad as Calpico, because the original name lands badly in English for reasons the company worked out late.",
  [("Calpis concentrate", "1.5 oz / 45 ml"), ("Cold water", "6 oz / 180 ml"),
   ("Ice", "cubed")],
  ["Fill a tall glass with ice.",
   "Pour the concentrate over.",
   "Add cold water — roughly four parts to one — and stir.",
   "Use soda water instead for Calpis Soda."],
  "A lemon wheel")

B("Ramune", "Japan", "Japan", "Party", "uncommon", "0%",
  "Lemon-lime soda sealed by a glass marble that you punch into the neck to open.",
  ["lemon", "lime", "soda"], "Ramune bottle",
  ["Lemon-lime soda"],
  "The Codd-neck bottle is held shut by its own carbonation pressing a marble against a rubber seal, and the marble stays rattling in the neck for the rest of the drink.",
  [("Ramune", "1 bottle / 200 ml"), ("Ice", "to chill the bottle")],
  ["Chill the bottle thoroughly — it will foam over if it is warm.",
   "Peel the wrapper and fit the plastic plunger into the top.",
   "Push down hard and fast to drive the marble into the neck.",
   "Hold it upright for a moment while it foams, then drink from the bottle."],
  "None — the marble is the point")

# =============================================================== EUROPE

B("Barley Water", UK, "England", "Regional", "uncommon", "0%",
  "Barley boiled with lemon peel and sugar, strained and served cold. Wimbledon has poured it since 1935.",
  ["barley", "lemon", "sugar"], "Tall glass",
  ["Pearl barley", "Lemon", "Sugar", "Water"],
  "Robinsons has been the Wimbledon barley water since 1935, when it was first sold there as a drink for players rather than spectators.",
  [("Pearl barley", "0.5 cup"), ("Water", "6 cups"),
   ("Lemons", "2, peeled and juiced"), ("Sugar", "0.5 cup"),
   ("Ice", "cubed")],
  ["Rinse the barley, cover with the water and simmer for 30 minutes.",
   "Add the lemon peel and simmer another 10 minutes.",
   "Strain, stir in the sugar and lemon juice while still hot, and discard the barley.",
   "Cool completely and serve over ice."],
  "A lemon wheel")

C("Kompot", "Poland", "Poland", "Regional", "common", "0%",
  "Fruit simmered in water with a little sugar and served cold. Every Polish household makes it and none the same way.",
  ["stone fruit", "berry", "sugar"], "Tall glass",
  ["Seasonal fruit", "Sugar", "Water"],
  "It is what happens to fruit that is too ripe to keep, which is why the recipe is different in every kitchen and formalised in none of them.",
  [("Mixed fruit", "1 lb / 450 g"), ("Water", "8 cups"),
   ("Sugar", "0.5 cup"), ("Cinnamon stick", "1"),
   ("Cloves", "3")],
  ["Put the fruit, sugar and spices in a pot with the water.",
   "Bring to a boil, then simmer for 20 minutes until the fruit gives up its colour.",
   "Take it off the heat and leave it to cool with the fruit still in.",
   "Strain or don't, chill, and serve cold with a few pieces of the fruit in the glass."],
  "A few pieces of the cooked fruit", "boiled")

B("Switchel", US, "New England, USA", "Regional", "rare", "0%",
  "Water, cider vinegar, ginger and molasses. What American farmhands drank in the hayfield before anyone sold sports drinks.",
  ["ginger", "vinegar", "molasses"], "Tall glass",
  ["Cider vinegar", "Ginger", "Molasses", "Water"],
  "It was known as haymaker's punch and drunk warm as often as cold, on the reasoning that a cold drink in the heat was dangerous.",
  [("Cider vinegar", "2 tbsp"), ("Molasses or maple syrup", "2 tbsp"),
   ("Fresh ginger", "1 tsp, grated"), ("Cold water", "8 oz / 240 ml"),
   ("Ice", "cubed")],
  ["Whisk the vinegar, molasses and grated ginger together until smooth.",
   "Add the cold water and stir well.",
   "Let it sit for an hour so the ginger infuses, then strain.",
   "Serve over ice, or warm on a cold day as it was originally drunk."],
  "A lemon wheel")

B("Shrub", US, "Philadelphia, USA", "Regional", "rare", "0%",
  "Drinking vinegar cut with soda. A colonial way of keeping fruit that turned out to be a good drink.",
  ["berry", "vinegar", "sugar"], "Tall glass",
  ["Fruit", "Vinegar", "Sugar", "Soda water"],
  "Vinegar preserves the fruit and the sugar preserves the vinegar, which is why a shrub keeps for a year without refrigeration and why colonial households made it by the gallon.",
  [("Raspberries", "2 cups"), ("Sugar", "1 cup"),
   ("Cider vinegar", "1 cup"), ("Soda water", "5 oz / 150 ml, to top"),
   ("Ice", "cubed")],
  ["Mash the fruit with the sugar and leave it, covered, for two days until it releases its syrup.",
   "Strain, pressing the fruit, then stir in the vinegar. Bottle it and leave a week to mellow.",
   "To serve, pour one ounce of shrub over ice.",
   "Top with soda water and stir once."],
  "A few fresh berries")

B("Sarsaparilla", US, "USA", "Retro", "rare", "0%",
  "Root-brewed soda with a medicinal edge. The drink that root beer came from and then left behind.",
  ["sassafras", "liquorice", "vanilla"], "Tall glass",
  ["Sarsaparilla root", "Sugar", "Water"],
  "It was sold as a blood purifier in nineteenth-century pharmacies, and the flavour still reads as medicine to anyone who did not grow up with it.",
  [("Sarsaparilla root", "2 oz / 55 g"), ("Liquorice root", "1 tbsp"),
   ("Water", "8 cups"), ("Sugar", "1.5 cups"),
   ("Vanilla extract", "1 tsp"), ("Soda water", "to serve")],
  ["Simmer the roots in the water for 30 minutes.",
   "Strain and stir in the sugar and vanilla while hot.",
   "Cool completely — this is the syrup, and it keeps for weeks.",
   "Serve one part syrup to four parts soda water, over plenty of ice."],
  "None")

B("Root Beer", US, "Philadelphia, USA", "Retro", "common", "0%",
  "Sassafras, wintergreen and vanilla brewed into a foaming soda. Deeply American and baffling everywhere else.",
  ["sassafras", "wintergreen", "vanilla"], "Frosted mug",
  ["Sassafras", "Wintergreen", "Vanilla", "Sugar"],
  "Safrole, the compound that gave real sassafras its flavour, was banned by the FDA in 1960 — every root beer since uses safrole-free extract.",
  [("Sassafras-free root beer extract", "2 tbsp"), ("Sugar", "1.5 cups"),
   ("Water", "8 cups"), ("Vanilla extract", "1 tsp"),
   ("Soda water", "to carbonate")],
  ["Dissolve the sugar in warm water and stir in the extract and vanilla.",
   "Cool completely to make the syrup.",
   "Mix one part syrup to four parts cold soda water.",
   "Serve in a mug that has been in the freezer, which is not optional."],
  "None — a frosted mug is the whole presentation")

B("Birch Beer", US, "Pennsylvania, USA", "Retro", "rare", "0%",
  "Birch bark soda, sharper and more minty than root beer. Comes red, brown or clear depending on the county.",
  ["birch", "wintergreen", "vanilla"], "Frosted mug",
  ["Birch bark", "Sugar", "Water"],
  "Pennsylvania Dutch country takes the colour seriously — red birch beer and white birch beer are different drinks there, and people hold opinions.",
  [("Birch bark", "3 oz / 85 g"), ("Water", "8 cups"),
   ("Sugar", "1.5 cups"), ("Wintergreen extract", "0.5 tsp"),
   ("Soda water", "to serve")],
  ["Simmer the birch bark in the water for 30 minutes.",
   "Strain and stir in the sugar and wintergreen while hot.",
   "Cool completely to make the syrup.",
   "Serve one part syrup to four parts soda water over ice, in a frosted mug."],
  "None")

B("Champola", "Cuba", "Cuba", "Regional", "rare", "0%",
  "Soursop pulp blended with milk and sugar. Cuba's answer to a milkshake, made from a fruit that tastes faintly of pineapple.",
  ["soursop", "milk", "vanilla"], "Tall glass",
  ["Soursop", "Milk", "Sugar"],
  "Soursop flesh has to be pulled apart and the seeds picked out by hand — they are mildly toxic and never go in the blender.",
  [("Soursop pulp", "1 cup, seeded"), ("Cold milk", "8 oz / 240 ml"),
   ("Sugar", "2 tbsp"), ("Vanilla extract", "0.5 tsp"),
   ("Ice", "1 cup")],
  ["Pull the soursop flesh apart by hand and remove every seed.",
   "Blend the pulp with the milk, sugar and vanilla until smooth.",
   "Add ice and blend again briefly.",
   "Pour into a tall glass and serve at once."],
  "A dusting of cinnamon")

B("Batido", "Venezuela", "Venezuela", "Frozen", "common", "0%",
  "Tropical fruit blended with ice and a little water or milk. The everyday drink of a Venezuelan lunch counter.",
  ["tropical fruit", "lime", "sugar"], "Tall glass",
  ["Fruit", "Water or milk", "Sugar", "Ice"],
  "A batido made with water is called a batido de agua and one with milk a merengada, and ordering the wrong one gets you a different drink entirely.",
  [("Ripe fruit", "1.5 cups, chopped"), ("Cold water or milk", "6 oz / 180 ml"),
   ("Sugar", "1 tbsp"), ("Lime juice", "1 tsp"), ("Ice", "1 cup")],
  ["Put the fruit, liquid, sugar and lime in a blender.",
   "Add the ice and blend until smooth and thick.",
   "Taste and adjust — ripe fruit often needs no sugar at all.",
   "Pour into a tall glass and drink cold."],
  "A wedge of the fruit used")
