#!/usr/bin/env bash
#
# Build Sipply for a real iPhone or for the Simulator, and install it.
#
#   scripts/build-ios.sh device   # Release, signed, installed over devicectl
#   scripts/build-ios.sh sim      # Release, unsigned, installed on a booted sim
#   scripts/build-ios.sh archive  # Release, distribution-signed, exported .ipa
#
# `archive` stops at the .ipa. It does NOT upload — that needs App Store
# Connect credentials, so the last leg is yours: Xcode Organizer, or
# `xcrun altool`/`notarytool` with an ASC API key.
#
# TAKE THE BUILD LOCK FIRST. Several sessions share this machine and one
# Xcode build lock, which lives inside the shared node_modules and is not
# isolated by git worktrees:
#
#     /tmp/drinkdex-build-lock.sh acquire "who you are"
#     scripts/build-ios.sh device
#     /tmp/drinkdex-build-lock.sh release
#
# The `pgrep` guard below is NOT a substitute. It is check-then-act: two
# builds started within the same prebuild window both see a clear machine
# and both proceed. Worse, it makes this script look like it already
# handles coordination, so nobody looks for the lock — which is exactly how
# two sessions each waited 26 minutes behind a third that had not taken it.
#
# The lock lives in /tmp because it is machine state, not repo state. It
# does not survive a reboot; recreate it if it is missing.
#
# IF THE INSTALL FAILS, DO NOT REBUILD. The build and the install are
# separate legs and they fail for unrelated reasons. A dropped tunnel looks
# nothing like a bad build:
#
#     ** BUILD SUCCEEDED **
#     ERROR: A connection to this device could not be established.
#            CoreDeviceError 4000 / NWError 54 — connection reset by peer
#
# That is 35 minutes of good work sitting on disk behind a transient network
# error, and this script exits without saying the .app is fine. Check the
# artifact and rerun the install alone:
#
#     ls -l ios/build/Build/Products/Release-iphoneos/Sipply.app/Sipply
#     xcrun devicectl device install app --device <UDID> <path>/Sipply.app
#
# The hollow-bundle check below already knows how to tell a real .app from a
# stump — it just runs before the install rather than after it. Other install
# failures worth recognising: kAMDMobileImageMounterDeviceLocked means unlock
# the phone (iOS will not mount the developer disk image until the handset
# has been unlocked once since boot), and that is a hardware state, not a bug.
#
# Four things this wrapper exists to remember, each of which cost a failed
# build to learn:
#
#  1. LANG. CocoaPods calls String#unicode_normalize, which raises
#     "Unicode Normalization not appropriate for ASCII-8BIT" when the shell
#     has no UTF-8 locale. Non-login shells here have LANG unset and
#     LC_CTYPE=C, so `pod install` dies inside `expo prebuild`.
#
#  2. DEVELOPMENT_TEAM is NOT in app.json, and `ios/` is gitignored and
#     regenerated by prebuild — so a `prebuild --clean` wipes the team and
#     the next build fails with "Signing for Sipply requires a development
#     team." It is read from ExportOptions.plist at the repo root, which is
#     tracked precisely because it has to survive a prebuild.
#
#  3. NEVER `-destination "id=<device-udid>"`. xcodebuild resolves that
#     through Xcode's device list, which reports the phone offline whenever
#     it has not been plugged in and unlocked recently — and then fails with
#     "Timed out waiting for all destinations". devicectl reaches the same
#     phone over its own tunnel, so build for a GENERIC device and let
#     devicectl do the install.
#
#  4. Release, always. A Debug build has no bundled JS and needs Metro on
#     this Mac, so it dies the moment the phone leaves the desk.
#
# One more, not enforceable here: do not start this while another xcodebuild
# is running against this repo. The lock lives at
# node_modules/expo-modules-jsi/apple/.DerivedData/.../XCBuildData/build.db,
# INSIDE node_modules, so a separate -derivedDataPath does not isolate it.

set -euo pipefail

MODE="${1:-device}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if pgrep -f "xcodebuild.*Sipply" >/dev/null 2>&1; then
  echo "Another xcodebuild is already running against this repo. Wait for it." >&2
  exit 1
fi

TEAM="$(/usr/libexec/PlistBuddy -c 'Print :teamID' ExportOptions.plist)"

if [ ! -d ios ]; then
  echo "==> ios/ is missing; running prebuild"
  npx expo prebuild -p ios
fi

case "$MODE" in
  device)
    echo "==> Building Release for a generic iOS device (team $TEAM)"
    xcodebuild -workspace ios/Sipply.xcworkspace -scheme Sipply \
      -configuration Release -destination 'generic/platform=iOS' \
      -allowProvisioningUpdates -derivedDataPath ios/build \
      DEVELOPMENT_TEAM="$TEAM" CODE_SIGN_STYLE=Automatic build

    APP="ios/build/Build/Products/Release-iphoneos/Sipply.app"
    # A killed build leaves a hollow bundle rather than no bundle at all.
    [ -s "$APP/Sipply" ] || { echo "No binary in $APP — build did not finish." >&2; exit 1; }

    # Match the UDID by SHAPE, never by field position. devicectl's columns
    # are whitespace-separated but two of them hold variable-length names:
    # the device name ("MC iPhone") and the model ("iPhone 17 Pro Max"). With
    # $(NF-3) this returned "17" — the number out of the model name — and
    # devicectl failed with 'device was not found (Name: 17)'. The build had
    # succeeded; only the install died, which makes it look like a build bug.
    #
    # devicectl reports TWO installable states and the pattern must accept
    # both: "available (paired)" when the phone is idle, and "connected"
    # when it is actively tunnelled. Matching only the first would fail to
    # resolve a phone that is awake and attached.
    #
    # This is a LATENT bug, fixed before it bit anyone. It is not the cause
    # of any install failure seen so far: the "Name: 17" failure was the
    # field-position parse fixed in 890eec6, and the DDI mount failure after
    # that was kAMDMobileImageMounterDeviceLocked — a genuinely locked phone,
    # correctly reported. If an install fails here, read the actual error
    # before suspecting this awk.
    #
    # "unavailable" must NOT match, which is why the first alternative keeps
    # "(paired)" rather than testing for "available" alone; "disconnected" is
    # excluded by the leading word boundary.
    DEV="$(xcrun devicectl list devices 2>/dev/null \
           | awk '/available \(paired\)|(^| )connected( |$)/ {
                    for (i = 1; i <= NF; i++)
                      if ($i ~ /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/) {
                        print $i; exit
                      }
                  }')"
    [ -n "$DEV" ] || {
      echo "No installable device. Plug the phone in, unlock it, trust this Mac." >&2
      echo "What devicectl can see:" >&2
      xcrun devicectl list devices >&2 2>/dev/null
      exit 1
    }

    echo "==> Installing to $DEV"
    # `install`, not `launch`: devicectl installs onto a locked phone, which
    # is why this is the reliable path. Tap the icon yourself.
    xcrun devicectl device install app --device "$DEV" "$APP"
    ;;

  sim)
    UDID="$(xcrun simctl list devices booted -j \
            | python3 -c 'import json,sys; d=json.load(sys.stdin)["devices"]; print(next((x["udid"] for v in d.values() for x in v), ""))')"
    [ -n "$UDID" ] || { echo "No booted simulator. Boot one first." >&2; exit 1; }

    echo "==> Building Release for simulator $UDID"
    xcodebuild -workspace ios/Sipply.xcworkspace -scheme Sipply \
      -configuration Release -destination "platform=iOS Simulator,id=$UDID" \
      -derivedDataPath ios/build-sim CODE_SIGNING_ALLOWED=NO build

    APP="ios/build-sim/Build/Products/Release-iphonesimulator/Sipply.app"
    xcrun simctl install "$UDID" "$APP"
    xcrun simctl launch "$UDID" com.janmcqueeny.drinkdex
    ;;

  archive)
    # Everything in `device` applies here too — the LANG export, the team read
    # out of ExportOptions.plist, and the generic destination. Three things are
    # different, and each is the kind of detail that costs a whole build:
    #
    #  1. ARCHIVE STRAIGHT INTO THE ORGANIZER'S FOLDER. Organizer only lists
    #     archives under ~/Library/Developer/Xcode/Archives/<date>/. An archive
    #     written anywhere else is invisible to it, and since Organizer is the
    #     upload path, an archive it cannot see may as well not exist. Building
    #     there directly is simpler than building elsewhere and remembering to
    #     copy it.
    #
    #  2. -allowProvisioningUpdates ON BOTH LEGS. ExportOptions.plist asks for
    #     automatic signing, and the DEVELOPMENT profile that `device` builds
    #     with is not valid for distribution. Xcode has to mint a distribution
    #     profile, and it will only do that with this flag — on the export as
    #     well as the archive, because export re-signs.
    #
    #  3. A SEPARATE derivedDataPath. Sharing ios/build with `device` means a
    #     distribution-signed archive and a development-signed .app fighting
    #     over the same intermediates. They are different signing identities;
    #     let them have different folders.
    #
    # The build number is echoed before any work starts. App Store Connect
    # rejects a duplicate CFBundleVersion, and it does so at UPLOAD — after
    # the archive, after the export, after you have waited. manageAppVersion-
    # AndBuildNumber is false in ExportOptions.plist, so nothing bumps it for
    # you: whatever is in app.json is what ships. Read the line and check it
    # against what TestFlight already holds before walking away.
    VERSION="$(node -p "require('$ROOT/app.json').expo.version")"
    BUILD="$(node -p "require('$ROOT/app.json').expo.ios.buildNumber")"

    STAMP="$(date '+%Y-%m-%d')"
    ARCHIVE_DIR="$HOME/Library/Developer/Xcode/Archives/$STAMP"
    ARCHIVE="$ARCHIVE_DIR/Sipply $VERSION ($BUILD) $(date '+%H.%M').xcarchive"
    EXPORT_DIR="$ROOT/ios/build-archive/export"

    mkdir -p "$ARCHIVE_DIR"

    echo "==> Archiving Sipply $VERSION ($BUILD) for the App Store (team $TEAM)"
    echo "    If TestFlight already holds build $BUILD, stop now and bump"
    echo "    ios.buildNumber in app.json — the upload will be refused."

    xcodebuild -workspace ios/Sipply.xcworkspace -scheme Sipply \
      -configuration Release -destination 'generic/platform=iOS' \
      -allowProvisioningUpdates -derivedDataPath ios/build-archive \
      -archivePath "$ARCHIVE" \
      DEVELOPMENT_TEAM="$TEAM" CODE_SIGN_STYLE=Automatic archive

    # Same lesson as the device leg: a killed build leaves a stump, not
    # nothing. An .xcarchive with no binary inside it still looks like a
    # directory that exists.
    [ -s "$ARCHIVE/Products/Applications/Sipply.app/Sipply" ] || {
      echo "No binary inside $ARCHIVE — the archive did not finish." >&2
      exit 1
    }

    echo "==> Exporting .ipa"
    rm -rf "$EXPORT_DIR"
    xcodebuild -exportArchive -archivePath "$ARCHIVE" \
      -exportOptionsPlist ExportOptions.plist \
      -exportPath "$EXPORT_DIR" \
      -allowProvisioningUpdates

    IPA="$(find "$EXPORT_DIR" -maxdepth 1 -name '*.ipa' | head -1)"
    [ -n "$IPA" ] || { echo "Export produced no .ipa. Read the log above." >&2; exit 1; }

    echo
    echo "==> Done. Sipply $VERSION ($BUILD)"
    echo "    Archive: $ARCHIVE"
    echo "    IPA:     $IPA"
    echo
    echo "    Upload is not automated — it needs App Store Connect credentials."
    echo "    Xcode > Window > Organizer will list the archive above; or use an"
    echo "    ASC API key with xcrun altool."
    ;;

  *)
    echo "Usage: scripts/build-ios.sh [device|sim|archive]" >&2
    exit 1
    ;;
esac
