import type { BeerBrand, BeerCountry, Brewery } from '@/types';

import raw from './breweries.json';

/**
 * The brand layer — real beers, by brewery, by country.
 *
 * Generated by `scripts/build-breweries.mjs`; edit the sources in
 * `scripts/beerdata/` and rebuild rather than editing the JSON, or the next
 * build silently reverts you.
 *
 * This is the Dex's other axis. `drinks.json` holds 100 beer STYLES with the
 * serve guides and compositions written out; this holds the products people
 * actually buy, each pointing back at its style through `styleRef`. Neither
 * duplicates the other.
 */
export const BEER_COUNTRIES: BeerCountry[] = (raw as unknown as BeerCountry[])
  .slice()
  .sort((a, b) => a.country.localeCompare(b.country));

/* Sorted, not data-ordered: the raw order follows whichever country happens
 * to sort first inside each region, which looks arbitrary in the filter row. */
export const BEER_REGIONS: string[] = [...new Set(BEER_COUNTRIES.map((c) => c.region))].sort(
  (a, b) => a.localeCompare(b)
);

export const BREWERY_COUNT = BEER_COUNTRIES.reduce((n, c) => n + c.breweries.length, 0);

export const BEER_BRAND_COUNT = BEER_COUNTRIES.reduce(
  (n, c) => n + c.breweries.reduce((m, b) => m + b.beers.length, 0),
  0
);

export const BEER_COUNTRIES_BY_CODE: Record<string, BeerCountry> = Object.fromEntries(
  BEER_COUNTRIES.map((c) => [c.code, c])
);

/** Flat brewery index, for detail routes and search. */
export const BREWERIES_BY_ID: Record<string, Brewery & { country: string; code: string }> =
  Object.fromEntries(
    BEER_COUNTRIES.flatMap((c) =>
      c.breweries.map((b) => [b.id, { ...b, country: c.country, code: c.code }] as const)
    )
  );

/** Every brand, flattened, each carrying where it comes from. */
export interface FlatBrand extends BeerBrand {
  brewery: string;
  breweryId: string;
  country: string;
  code: string;
  region: string;
}

export const BEER_BRANDS: FlatBrand[] = BEER_COUNTRIES.flatMap((c) =>
  c.breweries.flatMap((b) =>
    b.beers.map((x) => ({
      ...x,
      brewery: b.name,
      breweryId: b.id,
      country: c.country,
      code: c.code,
      region: c.region,
    }))
  )
);

/**
 * Brands that pour a given Dex style, so a style entry can show what to
 * actually go and buy. Keyed by `Drink.id`.
 */
export const BRANDS_BY_STYLE: Record<string, FlatBrand[]> = BEER_BRANDS.reduce(
  (acc, b) => {
    if (!b.styleRef) return acc;
    (acc[b.styleRef] ??= []).push(b);
    return acc;
  },
  {} as Record<string, FlatBrand[]>
);

/**
 * Accent-insensitive fold, so "niksicko" finds Nikšićko and "olfabrikken"
 * finds Ølfabrikken. NFD strips combining marks; the map handles the
 * standalone letters NFD leaves alone (æ, ø, ł are letters, not accents).
 */
const TRANS: Record<string, string> = {
  æ: 'ae',
  ø: 'o',
  ł: 'l',
  đ: 'd',
  ð: 'd',
  þ: 'th',
  ß: 'ss',
  œ: 'oe',
};

export function fold(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[æøłđðþßœ]/g, (c) => TRANS[c] ?? c);
}

/** Countries whose lineups have been researched product-by-product. */
export const RESEARCHED_COUNTRIES: string[] = BEER_COUNTRIES.filter((c) =>
  c.breweries.some((b) => b.researched)
).map((c) => c.country);
