import type { AtlasLink } from '@/types';

import raw from './wineAtlasLinks.json';

/**
 * Wine Dex card -> atlas.
 *
 * Generated by scripts/build-wine-atlas-links.mjs. Seven cards carry
 * `absent` instead of links: the five sakes, which are brewed from rice,
 * and the two vermouths, which are aromatized rather than appellation
 * wines. They say so on the card rather than pointing at something
 * approximate.
 */
export const ATLAS_LINKS = raw as unknown as Record<string, AtlasLink>;

export function atlasLinkFor(drinkId: string): AtlasLink | undefined {
  return ATLAS_LINKS[drinkId];
}
